// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const D3D_FL9_1_REQ_TEXTURE1D_U_DIMENSION = 0x800;
const D3D_FL9_3_REQ_TEXTURE1D_U_DIMENSION = 0x1000;
const D3D_FL9_1_REQ_TEXTURE2D_U_OR_V_DIMENSION = 0x800;
const D3D_FL9_3_REQ_TEXTURE2D_U_OR_V_DIMENSION = 0x1000;
const D3D_FL9_1_REQ_TEXTURECUBE_DIMENSION = 0x200;
const D3D_FL9_3_REQ_TEXTURECUBE_DIMENSION = 0x1000;
const D3D_FL9_1_REQ_TEXTURE3D_U_V_OR_W_DIMENSION = 0x100;
const D3D_FL9_1_DEFAULT_MAX_ANISOTROPY = 0x2;
const D3D_FL9_1_IA_PRIMITIVE_MAX_COUNT = 0xffff;
const D3D_FL9_2_IA_PRIMITIVE_MAX_COUNT = 0xfffff;
const D3D_FL9_1_SIMULTANEOUS_RENDER_TARGET_COUNT = 0x1;
const D3D_FL9_3_SIMULTANEOUS_RENDER_TARGET_COUNT = 0x4;
const D3D_FL9_1_MAX_TEXTURE_REPEAT = 0x80;
const D3D_FL9_2_MAX_TEXTURE_REPEAT = 0x800;
const D3D_FL9_3_MAX_TEXTURE_REPEAT = 0x2000;
const D3D_SHADER_FEATURE_DOUBLES = 0x1;
const D3D_SHADER_FEATURE_COMPUTE_SHADERS_PLUS_RAW_AND_STRUCTURED_BUFFERS_VIA_SHADER_4_X =
    0x2;
const D3D_SHADER_FEATURE_UAVS_AT_EVERY_STAGE = 0x4;
const D3D_SHADER_FEATURE_64_UAVS = 0x8;
const D3D_SHADER_FEATURE_MINIMUM_PRECISION = 0x10;
const D3D_SHADER_FEATURE_11_1_DOUBLE_EXTENSIONS = 0x20;
const D3D_SHADER_FEATURE_11_1_SHADER_EXTENSIONS = 0x40;
const D3D_SHADER_FEATURE_LEVEL_9_COMPARISON_FILTERING = 0x80;
const D3D_SHADER_FEATURE_TILED_RESOURCES = 0x100;
const D3D_SHADER_FEATURE_STENCIL_REF = 0x200;
const D3D_SHADER_FEATURE_INNER_COVERAGE = 0x400;
const D3D_SHADER_FEATURE_TYPED_UAV_LOAD_ADDITIONAL_FORMATS = 0x800;
const D3D_SHADER_FEATURE_ROVS = 0x1000;
const D3D_SHADER_FEATURE_VIEWPORT_AND_RT_ARRAY_INDEX_FROM_ANY_SHADER_FEEDING_RASTERIZER =
    0x2000;
const D3D_SHADER_FEATURE_WAVE_OPS = 0x4000;
const D3D_SHADER_FEATURE_INT64_OPS = 0x8000;
const D3D_SHADER_FEATURE_VIEW_ID = 0x10000;
const D3D_SHADER_FEATURE_BARYCENTRICS = 0x20000;
const D3D_SHADER_FEATURE_NATIVE_16BIT_OPS = 0x40000;
const D3D_SHADER_FEATURE_SHADING_RATE = 0x80000;
const D3D_SHADER_FEATURE_RAYTRACING_TIER_1_1 = 0x100000;
const D3D_SHADER_FEATURE_SAMPLER_FEEDBACK = 0x200000;
const D3D_SHADER_FEATURE_ATOMIC_INT64_ON_TYPED_RESOURCE = 0x400000;
const D3D_SHADER_FEATURE_ATOMIC_INT64_ON_GROUP_SHARED = 0x800000;
const D3D_SHADER_FEATURE_DERIVATIVES_IN_MESH_AND_AMPLIFICATION_SHADERS =
    0x1000000;
const D3D_SHADER_FEATURE_RESOURCE_DESCRIPTOR_HEAP_INDEXING = 0x2000000;
const D3D_SHADER_FEATURE_SAMPLER_DESCRIPTOR_HEAP_INDEXING = 0x4000000;
const D3D_SHADER_FEATURE_WAVE_MMA = 0x8000000;
const D3D_SHADER_FEATURE_ATOMIC_INT64_ON_DESCRIPTOR_HEAP_RESOURCE = 0x10000000;
const WKPDID_D3DDebugObjectName = 0x0;
const WKPDID_D3DDebugObjectNameW = 0x0;
const WKPDID_CommentStringW = 0x0;
const WKPDID_D3D12UniqueObjectId = 0x0;
const D3D_COMPONENT_MASK_X = 0x1;
const D3D_COMPONENT_MASK_Y = 0x2;
const D3D_COMPONENT_MASK_Z = 0x4;
const D3D_COMPONENT_MASK_W = 0x8;
const D3D_TEXTURE_LAYOUT_ROW_MAJOR = 0x0;
const D3D_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE = 0x0;
