/// An exception generated by the `generator` package.
class GeneratorException implements Exception {
  const GeneratorException(this.message);

  /// A message describing the exception.
  final String message;

  @override
  String toString() => 'GeneratorException: $message';
}
