- name: com
  color: '8C9FDB'
  description: Issue with COM support

- name: 'package: ffi_leak_tracker'
  color: '2FE436'
  description: Issue with package:ffi_leak_tracker

- name: 'package: generator'
  color: '2FE436'
  description: Issue with package:generator

- name: 'package: win32'
  color: '2FE436'
  description: Issue with package:win32

- name: 'package: win32_clipboard'
  color: '2FE436'
  description: Issue with package:win32_clipboard

- name: 'package: win32_registry'
  color: '2FE436'
  description: Issue with package:win32_registry

- name: 'package: win32_runner'
  color: '2FE436'
  description: Issue with package:win32_runner

- name: 'package: winmd'
  color: '2FE436'
  description: Issue with package:winmd

- name: website
  color: '006b75'
  description: Issue with https://win32.pub
