ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - packages/*/cliff.toml
          - codecov.yml
          - lefthook.yml

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - packages/*/doc/*
          - packages/*/PUBLISHING.md
          - website/docs/**
          - CONTRIBUTING.md
          - README.md

example:
  - changed-files:
      - any-glob-to-any-file:
          - examples/**
          - packages/*/example/**

'external dependency':
  - head-branch: [^dependabot]

'package: ffi_leak_tracker':
  - changed-files:
      - any-glob-to-any-file: packages/ffi_leak_tracker/**

'package: filepicker_windows':
  - changed-files:
      - any-glob-to-any-file: packages/filepicker_windows/**

'package: generator':
  - changed-files:
      - any-glob-to-any-file: packages/generator/**

'package: win32':
  - changed-files:
      - any-glob-to-any-file: packages/win32/**

'package: win32_clipboard':
  - changed-files:
      - any-glob-to-any-file: packages/win32_clipboard/**

'package: win32_gamepad':
  - changed-files:
      - any-glob-to-any-file: packages/win32_gamepad/**

'package: win32_registry':
  - changed-files:
      - any-glob-to-any-file: packages/win32_registry/**

'package: win32_runner':
  - changed-files:
      - any-glob-to-any-file: packages/win32_runner/**

'package: winmd':
  - changed-files:
      - any-glob-to-any-file: packages/winmd/**

release:
  - head-branch: [^release, release]

test:
  - changed-files:
      - any-glob-to-all-files:
          - packages/*/test/**

website:
  - changed-files:
      - any-glob-to-any-file: website/**
