ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - cliff.toml
          - codecov.yml
          - lefthook.yml

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - packages/win32/doc/*
          - website/docs/**
          - CONTRIBUTING.md
          - PUBLISHING.md
          - README.md

example:
  - changed-files:
      - any-glob-to-any-file: examples/**

'external dependency':
  - head-branch: [^dependabot]

'package: generator':
  - changed-files:
      - any-glob-to-any-file: packages/generator/**

'package: win32':
  - changed-files:
      - any-glob-to-any-file: packages/win32/**

release:
  - head-branch: [^release, release]

test:
  - changed-files:
      - any-glob-to-all-files:
          - test/**

website:
  - changed-files:
      - any-glob-to-any-file: website/**
