include: package:halildurmus_lints/dart.yaml

analyzer:
  exclude: [examples/explorer/**, examples/task_manager/**]

linter:
  rules:
    - remove_deprecations_in_breaking_versions
    - switch_on_type
    - unnecessary_unawaited
