/// {@category Enum}
class GAMING_DEVICE_DEVICE_ID {
  static const GAMING_DEVICE_DEVICE_ID_NONE = 0x00000000;
  static const GAMING_DEVICE_DEVICE_ID_XBOX_ONE = 0x768bae26;
  static const GAMING_DEVICE_DEVICE_ID_XBOX_ONE_S = 0x2a7361d9;
  static const GAMING_DEVICE_DEVICE_ID_XBOX_ONE_X = 0x5ad617c7;
  static const GAMING_DEVICE_DEVICE_ID_XBOX_ONE_X_DEVKIT = 0x10f7cde3;
}

/// {@category Enum}
class GAMING_DEVICE_VENDOR_ID {
  static const GAMING_DEVICE_VENDOR_ID_NONE = 0x00000000;
  static const GAMING_DEVICE_VENDOR_ID_MICROSOFT = 0xc2ec5032;
}

