/// {@category Enum}
class XAML_REFERENCETRACKER_DISCONNECT {
  static const XAML_REFERENCETRACKER_DISCONNECT_DEFAULT = 0x00000000;
  static const XAML_REFERENCETRACKER_DISCONNECT_SUSPEND = 0x00000001;
}
