/// An exception generated by the `winmd` package.
class WinmdException implements Exception {
  const WinmdException(this.message);

  final String message;

  @override
  String toString() => 'WinmdException: $message';
}
