// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const DISPID_RDPSRAPI_METHOD_OPEN = 0x64;
const DISPID_RDPSRAPI_METHOD_CLOSE = 0x65;
const DISPID_RDPSRAPI_METHOD_SETSHAREDRECT = 0x66;
const DISPID_RDPSRAPI_METHOD_GETSHAREDRECT = 0x67;
const DISPID_RDPSRAPI_METHOD_VIEWERCONNECT = 0x68;
const DISPID_RDPSRAPI_METHOD_VIEWERDISCONNECT = 0x69;
const DISPID_RDPSRAPI_METHOD_TERMINATE_CONNECTION = 0x6a;
const DISPID_RDPSRAPI_METHOD_CREATE_INVITATION = 0x6b;
const DISPID_RDPSRAPI_METHOD_REQUEST_CONTROL = 0x6c;
const DISPID_RDPSRAPI_METHOD_VIRTUAL_CHANNEL_CREATE = 0x6d;
const DISPID_RDPSRAPI_METHOD_VIRTUAL_CHANNEL_SEND_DATA = 0x6e;
const DISPID_RDPSRAPI_METHOD_VIRTUAL_CHANNEL_SET_ACCESS = 0x6f;
const DISPID_RDPSRAPI_METHOD_PAUSE = 0x70;
const DISPID_RDPSRAPI_METHOD_RESUME = 0x71;
const DISPID_RDPSRAPI_METHOD_SHOW_WINDOW = 0x72;
const DISPID_RDPSRAPI_METHOD_REQUEST_COLOR_DEPTH_CHANGE = 0x73;
const DISPID_RDPSRAPI_METHOD_STARTREVCONNECTLISTENER = 0x74;
const DISPID_RDPSRAPI_METHOD_CONNECTTOCLIENT = 0x75;
const DISPID_RDPSRAPI_METHOD_SET_RENDERING_SURFACE = 0x76;
const DISPID_RDPSRAPI_METHOD_SEND_MOUSE_BUTTON_EVENT = 0x77;
const DISPID_RDPSRAPI_METHOD_SEND_MOUSE_MOVE_EVENT = 0x78;
const DISPID_RDPSRAPI_METHOD_SEND_MOUSE_WHEEL_EVENT = 0x79;
const DISPID_RDPSRAPI_METHOD_SEND_KEYBOARD_EVENT = 0x7a;
const DISPID_RDPSRAPI_METHOD_SEND_SYNC_EVENT = 0x7b;
const DISPID_RDPSRAPI_METHOD_BEGIN_TOUCH_FRAME = 0x7c;
const DISPID_RDPSRAPI_METHOD_ADD_TOUCH_INPUT = 0x7d;
const DISPID_RDPSRAPI_METHOD_END_TOUCH_FRAME = 0x7e;
const DISPID_RDPSRAPI_METHOD_CONNECTUSINGTRANSPORTSTREAM = 0x7f;
const DISPID_RDPSRAPI_METHOD_SENDCONTROLLEVELCHANGERESPONSE = 0x94;
const DISPID_RDPSRAPI_METHOD_GETFRAMEBUFFERBITS = 0x95;
const DISPID_RDPSRAPI_PROP_DISPIDVALUE = 0xc8;
const DISPID_RDPSRAPI_PROP_ID = 0xc9;
const DISPID_RDPSRAPI_PROP_SESSION_PROPERTIES = 0xca;
const DISPID_RDPSRAPI_PROP_ATTENDEES = 0xcb;
const DISPID_RDPSRAPI_PROP_INVITATIONS = 0xcc;
const DISPID_RDPSRAPI_PROP_INVITATION = 0xcd;
const DISPID_RDPSRAPI_PROP_CHANNELMANAGER = 0xce;
const DISPID_RDPSRAPI_PROP_VIRTUAL_CHANNEL_GETNAME = 0xcf;
const DISPID_RDPSRAPI_PROP_VIRTUAL_CHANNEL_GETFLAGS = 0xd0;
const DISPID_RDPSRAPI_PROP_VIRTUAL_CHANNEL_GETPRIORITY = 0xd1;
const DISPID_RDPSRAPI_PROP_WINDOWID = 0xd2;
const DISPID_RDPSRAPI_PROP_APPLICATION = 0xd3;
const DISPID_RDPSRAPI_PROP_WINDOWSHARED = 0xd4;
const DISPID_RDPSRAPI_PROP_WINDOWNAME = 0xd5;
const DISPID_RDPSRAPI_PROP_APPNAME = 0xd6;
const DISPID_RDPSRAPI_PROP_APPLICATION_FILTER = 0xd7;
const DISPID_RDPSRAPI_PROP_WINDOW_LIST = 0xd8;
const DISPID_RDPSRAPI_PROP_APPLICATION_LIST = 0xd9;
const DISPID_RDPSRAPI_PROP_APPFILTER_ENABLED = 0xda;
const DISPID_RDPSRAPI_PROP_APPFILTERENABLED = 0xdb;
const DISPID_RDPSRAPI_PROP_SHARED = 0xdc;
const DISPID_RDPSRAPI_PROP_INVITATIONITEM = 0xdd;
const DISPID_RDPSRAPI_PROP_DBG_CLX_CMDLINE = 0xde;
const DISPID_RDPSRAPI_PROP_APPFLAGS = 0xdf;
const DISPID_RDPSRAPI_PROP_WNDFLAGS = 0xe0;
const DISPID_RDPSRAPI_PROP_PROTOCOL_TYPE = 0xe1;
const DISPID_RDPSRAPI_PROP_LOCAL_PORT = 0xe2;
const DISPID_RDPSRAPI_PROP_LOCAL_IP = 0xe3;
const DISPID_RDPSRAPI_PROP_PEER_PORT = 0xe4;
const DISPID_RDPSRAPI_PROP_PEER_IP = 0xe5;
const DISPID_RDPSRAPI_PROP_ATTENDEE_FLAGS = 0xe6;
const DISPID_RDPSRAPI_PROP_CONINFO = 0xe7;
const DISPID_RDPSRAPI_PROP_CONNECTION_STRING = 0xe8;
const DISPID_RDPSRAPI_PROP_GROUP_NAME = 0xe9;
const DISPID_RDPSRAPI_PROP_PASSWORD = 0xea;
const DISPID_RDPSRAPI_PROP_ATTENDEELIMIT = 0xeb;
const DISPID_RDPSRAPI_PROP_REVOKED = 0xec;
const DISPID_RDPSRAPI_PROP_DISCONNECTED_STRING = 0xed;
const DISPID_RDPSRAPI_PROP_USESMARTSIZING = 0xee;
const DISPID_RDPSRAPI_PROP_SESSION_COLORDEPTH = 0xef;
const DISPID_RDPSRAPI_PROP_REASON = 0xf0;
const DISPID_RDPSRAPI_PROP_CODE = 0xf1;
const DISPID_RDPSRAPI_PROP_CTRL_LEVEL = 0xf2;
const DISPID_RDPSRAPI_PROP_REMOTENAME = 0xf3;
const DISPID_RDPSRAPI_PROP_COUNT = 0xf4;
const DISPID_RDPSRAPI_PROP_FRAMEBUFFER_HEIGHT = 0xfb;
const DISPID_RDPSRAPI_PROP_FRAMEBUFFER_WIDTH = 0xfc;
const DISPID_RDPSRAPI_PROP_FRAMEBUFFER_BPP = 0xfd;
const DISPID_RDPSRAPI_PROP_FRAMEBUFFER = 0xfe;
const DISPID_RDPSRAPI_EVENT_ON_ATTENDEE_CONNECTED = 0x12d;
const DISPID_RDPSRAPI_EVENT_ON_ATTENDEE_DISCONNECTED = 0x12e;
const DISPID_RDPSRAPI_EVENT_ON_ATTENDEE_UPDATE = 0x12f;
const DISPID_RDPSRAPI_EVENT_ON_ERROR = 0x130;
const DISPID_RDPSRAPI_EVENT_ON_VIEWER_CONNECTED = 0x131;
const DISPID_RDPSRAPI_EVENT_ON_VIEWER_DISCONNECTED = 0x132;
const DISPID_RDPSRAPI_EVENT_ON_VIEWER_AUTHENTICATED = 0x133;
const DISPID_RDPSRAPI_EVENT_ON_VIEWER_CONNECTFAILED = 0x134;
const DISPID_RDPSRAPI_EVENT_ON_CTRLLEVEL_CHANGE_REQUEST = 0x135;
const DISPID_RDPSRAPI_EVENT_ON_GRAPHICS_STREAM_PAUSED = 0x136;
const DISPID_RDPSRAPI_EVENT_ON_GRAPHICS_STREAM_RESUMED = 0x137;
const DISPID_RDPSRAPI_EVENT_ON_VIRTUAL_CHANNEL_JOIN = 0x138;
const DISPID_RDPSRAPI_EVENT_ON_VIRTUAL_CHANNEL_LEAVE = 0x139;
const DISPID_RDPSRAPI_EVENT_ON_VIRTUAL_CHANNEL_DATARECEIVED = 0x13a;
const DISPID_RDPSRAPI_EVENT_ON_VIRTUAL_CHANNEL_SENDCOMPLETED = 0x13b;
const DISPID_RDPSRAPI_EVENT_ON_APPLICATION_OPEN = 0x13c;
const DISPID_RDPSRAPI_EVENT_ON_APPLICATION_CLOSE = 0x13d;
const DISPID_RDPSRAPI_EVENT_ON_APPLICATION_UPDATE = 0x13e;
const DISPID_RDPSRAPI_EVENT_ON_WINDOW_OPEN = 0x13f;
const DISPID_RDPSRAPI_EVENT_ON_WINDOW_CLOSE = 0x140;
const DISPID_RDPSRAPI_EVENT_ON_WINDOW_UPDATE = 0x141;
const DISPID_RDPSRAPI_EVENT_ON_APPFILTER_UPDATE = 0x142;
const DISPID_RDPSRAPI_EVENT_ON_SHARED_RECT_CHANGED = 0x143;
const DISPID_RDPSRAPI_EVENT_ON_FOCUSRELEASED = 0x144;
const DISPID_RDPSRAPI_EVENT_ON_SHARED_DESKTOP_SETTINGS_CHANGED = 0x145;
const DISPID_RDPSRAPI_EVENT_ON_CTRLLEVEL_CHANGE_RESPONSE = 0x152;
const DISPID_RDPAPI_EVENT_ON_BOUNDING_RECT_CHANGED = 0x154;
const DISPID_RDPSRAPI_METHOD_STREAM_ALLOCBUFFER = 0x1a5;
const DISPID_RDPSRAPI_METHOD_STREAM_FREEBUFFER = 0x1a6;
const DISPID_RDPSRAPI_METHOD_STREAMSENDDATA = 0x1a7;
const DISPID_RDPSRAPI_METHOD_STREAMREADDATA = 0x1a8;
const DISPID_RDPSRAPI_METHOD_STREAMOPEN = 0x1a9;
const DISPID_RDPSRAPI_METHOD_STREAMCLOSE = 0x1aa;
const DISPID_RDPSRAPI_PROP_STREAMBUFFER_STORAGE = 0x22b;
const DISPID_RDPSRAPI_PROP_STREAMBUFFER_PAYLOADSIZE = 0x22e;
const DISPID_RDPSRAPI_PROP_STREAMBUFFER_PAYLOADOFFSET = 0x22f;
const DISPID_RDPSRAPI_PROP_STREAMBUFFER_CONTEXT = 0x230;
const DISPID_RDPSRAPI_PROP_STREAMBUFFER_FLAGS = 0x231;
const DISPID_RDPSRAPI_PROP_STREAMBUFFER_STORESIZE = 0x232;
const DISPID_RDPSRAPI_EVENT_ON_STREAM_SENDCOMPLETED = 0x278;
const DISPID_RDPSRAPI_EVENT_ON_STREAM_DATARECEIVED = 0x279;
const DISPID_RDPSRAPI_EVENT_ON_STREAM_CLOSED = 0x27a;
const DISPID_RDPSRAPI_EVENT_VIEW_MOUSE_BUTTON_RECEIVED = 0x2bc;
const DISPID_RDPSRAPI_EVENT_VIEW_MOUSE_MOVE_RECEIVED = 0x2bd;
const DISPID_RDPSRAPI_EVENT_VIEW_MOUSE_WHEEL_RECEIVED = 0x2be;
const RDPViewer = '{32BE5ED2-5C86-480F-A914-0FF8885A1B3F}';
const RDPSession = '{9B78F0E6-3E05-4A5B-B2E8-E743A8956B65}';
const RDPTransportStreamBuffer = '{8D4A1C69-F17F-4549-A699-761C6E6B5C0A}';
const RDPTransportStreamEvents = '{31E3AB20-5350-483F-9DC6-6748665EFDEB}';
