/// {@category Enum}
class OPERATION_END_PARAMETERS_FLAGS {
  static const OPERATION_END_DISCARD = 0x00000001;
}

/// {@category Enum}
class OPERATION_START_FLAGS {
  static const OPERATION_START_TRACE_CURRENT_THREAD = 0x00000001;
}
