// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const HTTP_DEMAND_CBT = 0x4;
const HTTP_MAX_SERVER_QUEUE_LENGTH = 0x7fffffff;
const HTTP_MIN_SERVER_QUEUE_LENGTH = 0x1;
const HTTP_AUTH_ENABLE_BASIC = 0x1;
const HTTP_AUTH_ENABLE_DIGEST = 0x2;
const HTTP_AUTH_ENABLE_NTLM = 0x4;
const HTTP_AUTH_ENABLE_NEGOTIATE = 0x8;
const HTTP_AUTH_ENABLE_KERBEROS = 0x10;
const HTTP_AUTH_EX_FLAG_ENABLE_KERBEROS_CREDENTIAL_CACHING = 0x1;
const HTTP_AUTH_EX_FLAG_CAPTURE_CREDENTIAL = 0x2;
const HTTP_CHANNEL_BIND_PROXY = 0x1;
const HTTP_CHANNEL_BIND_PROXY_COHOSTING = 0x20;
const HTTP_CHANNEL_BIND_NO_SERVICE_NAME_CHECK = 0x2;
const HTTP_CHANNEL_BIND_DOTLESS_SERVICE = 0x4;
const HTTP_CHANNEL_BIND_SECURE_CHANNEL_TOKEN = 0x8;
const HTTP_CHANNEL_BIND_CLIENT_SERVICE = 0x10;
const HTTP_LOG_FIELD_DATE = 0x1;
const HTTP_LOG_FIELD_TIME = 0x2;
const HTTP_LOG_FIELD_CLIENT_IP = 0x4;
const HTTP_LOG_FIELD_USER_NAME = 0x8;
const HTTP_LOG_FIELD_SITE_NAME = 0x10;
const HTTP_LOG_FIELD_COMPUTER_NAME = 0x20;
const HTTP_LOG_FIELD_SERVER_IP = 0x40;
const HTTP_LOG_FIELD_METHOD = 0x80;
const HTTP_LOG_FIELD_URI_STEM = 0x100;
const HTTP_LOG_FIELD_URI_QUERY = 0x200;
const HTTP_LOG_FIELD_STATUS = 0x400;
const HTTP_LOG_FIELD_WIN32_STATUS = 0x800;
const HTTP_LOG_FIELD_BYTES_SENT = 0x1000;
const HTTP_LOG_FIELD_BYTES_RECV = 0x2000;
const HTTP_LOG_FIELD_TIME_TAKEN = 0x4000;
const HTTP_LOG_FIELD_SERVER_PORT = 0x8000;
const HTTP_LOG_FIELD_USER_AGENT = 0x10000;
const HTTP_LOG_FIELD_COOKIE = 0x20000;
const HTTP_LOG_FIELD_REFERER = 0x40000;
const HTTP_LOG_FIELD_VERSION = 0x80000;
const HTTP_LOG_FIELD_HOST = 0x100000;
const HTTP_LOG_FIELD_SUB_STATUS = 0x200000;
const HTTP_LOG_FIELD_STREAM_ID = 0x8000000;
const HTTP_LOG_FIELD_STREAM_ID_EX = 0x10000000;
const HTTP_LOG_FIELD_TRANSPORT_TYPE = 0x20000000;
const HTTP_LOG_FIELD_CLIENT_PORT = 0x400000;
const HTTP_LOG_FIELD_URI = 0x800000;
const HTTP_LOG_FIELD_SITE_ID = 0x1000000;
const HTTP_LOG_FIELD_REASON = 0x2000000;
const HTTP_LOG_FIELD_QUEUE_NAME = 0x4000000;
const HTTP_LOG_FIELD_CORRELATION_ID = 0x40000000;
const HTTP_LOGGING_FLAG_LOCAL_TIME_ROLLOVER = 0x1;
const HTTP_LOGGING_FLAG_USE_UTF8_CONVERSION = 0x2;
const HTTP_LOGGING_FLAG_LOG_ERRORS_ONLY = 0x4;
const HTTP_LOGGING_FLAG_LOG_SUCCESS_ONLY = 0x8;
const HTTP_CREATE_REQUEST_QUEUE_FLAG_OPEN_EXISTING = 0x1;
const HTTP_CREATE_REQUEST_QUEUE_FLAG_CONTROLLER = 0x2;
const HTTP_CREATE_REQUEST_QUEUE_FLAG_DELEGATION = 0x8;
const HTTP_RECEIVE_REQUEST_ENTITY_BODY_FLAG_FILL_BUFFER = 0x1;
const HTTP_SEND_RESPONSE_FLAG_DISCONNECT = 0x1;
const HTTP_SEND_RESPONSE_FLAG_MORE_DATA = 0x2;
const HTTP_SEND_RESPONSE_FLAG_BUFFER_DATA = 0x4;
const HTTP_SEND_RESPONSE_FLAG_ENABLE_NAGLING = 0x8;
const HTTP_SEND_RESPONSE_FLAG_PROCESS_RANGES = 0x20;
const HTTP_SEND_RESPONSE_FLAG_OPAQUE = 0x40;
const HTTP_SEND_RESPONSE_FLAG_GOAWAY = 0x100;
const HTTP_FLUSH_RESPONSE_FLAG_RECURSIVE = 0x1;
const HTTP_URL_FLAG_REMOVE_ALL = 0x1;
const HTTP_RECEIVE_SECURE_CHANNEL_TOKEN = 0x1;
const HTTP_RECEIVE_FULL_CHAIN = 0x2;
const HTTP_REQUEST_SIZING_INFO_FLAG_TCP_FAST_OPEN = 0x1;
const HTTP_REQUEST_SIZING_INFO_FLAG_TLS_SESSION_RESUMPTION = 0x2;
const HTTP_REQUEST_SIZING_INFO_FLAG_TLS_FALSE_START = 0x4;
const HTTP_REQUEST_SIZING_INFO_FLAG_FIRST_REQUEST = 0x8;
const HTTP_REQUEST_AUTH_FLAG_TOKEN_FOR_CACHED_CRED = 0x1;
const HTTP_REQUEST_FLAG_MORE_ENTITY_BODY_EXISTS = 0x1;
const HTTP_REQUEST_FLAG_IP_ROUTED = 0x2;
const HTTP_REQUEST_FLAG_HTTP2 = 0x4;
const HTTP_REQUEST_FLAG_HTTP3 = 0x8;
const HTTP_RESPONSE_FLAG_MULTIPLE_ENCODINGS_AVAILABLE = 0x1;
const HTTP_RESPONSE_FLAG_MORE_ENTITY_BODY_EXISTS = 0x2;
const HTTP_RESPONSE_INFO_FLAGS_PRESERVE_ORDER = 0x1;
const HTTP_SERVICE_CONFIG_SSL_FLAG_USE_DS_MAPPER = 0x1;
const HTTP_SERVICE_CONFIG_SSL_FLAG_NEGOTIATE_CLIENT_CERT = 0x2;
const HTTP_SERVICE_CONFIG_SSL_FLAG_NO_RAW_FILTER = 0x4;
const HTTP_SERVICE_CONFIG_SSL_FLAG_REJECT = 0x8;
const HTTP_SERVICE_CONFIG_SSL_FLAG_DISABLE_HTTP2 = 0x10;
const HTTP_SERVICE_CONFIG_SSL_FLAG_DISABLE_QUIC = 0x20;
const HTTP_SERVICE_CONFIG_SSL_FLAG_DISABLE_TLS13 = 0x40;
const HTTP_SERVICE_CONFIG_SSL_FLAG_DISABLE_OCSP_STAPLING = 0x80;
const HTTP_SERVICE_CONFIG_SSL_FLAG_ENABLE_TOKEN_BINDING = 0x100;
const HTTP_SERVICE_CONFIG_SSL_FLAG_LOG_EXTENDED_EVENTS = 0x200;
const HTTP_SERVICE_CONFIG_SSL_FLAG_DISABLE_LEGACY_TLS = 0x400;
const HTTP_SERVICE_CONFIG_SSL_FLAG_ENABLE_SESSION_TICKET = 0x800;
const HTTP_SERVICE_CONFIG_SSL_FLAG_DISABLE_TLS12 = 0x1000;
const HTTP_SERVICE_CONFIG_SSL_FLAG_ENABLE_CLIENT_CORRELATION = 0x2000;
const HTTP_REQUEST_PROPERTY_SNI_HOST_MAX_LENGTH = 0xff;
const HTTP_REQUEST_PROPERTY_SNI_FLAG_SNI_USED = 0x1;
const HTTP_REQUEST_PROPERTY_SNI_FLAG_NO_SNI = 0x2;
