// api-ms-win-ro-typeresolution-l1-1-0 is missing in the metadata:
// https://github.com/microsoft/win32metadata/issues/240

const winmdGenerated = [
  'advapi32',
  'api-ms-win-core-winrt-l1-1-0',
  'api-ms-win-core-winrt-string-l1-1-0',
  // 'api-ms-win-ro-typeresolution-l1-1-0',
  'bthprops',
  'comctl32',
  'comdlg32',
  'dbghelp',
  'dwmapi',
  'dxva2',
  'gdi32',
  'kernel32',
  'kernelbase',
  'ole32',
  'oleaut32',
  'powrprof',
  'rometadata',
  'scarddlg',
  'shcore',
  'shell32',
  'spoolss',
  'user32',
  'uxtheme',
  'version',
  'winmm',
  'winscard',
  'winspool',
  'wlanapi',
  'ws2_32',
];
