// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const GPM_USE_PDC = 0x0;
const GPM_USE_ANYDC = 0x1;
const GPM_DONOTUSE_W2KDC = 0x2;
const GPM_DONOT_VALIDATEDC = 0x1;
const GPM_MIGRATIONTABLE_ONLY = 0x1;
const GPM_PROCESS_SECURITY = 0x2;
const RSOP_NO_COMPUTER = 0x10000;
const RSOP_NO_USER = 0x20000;
const RSOP_PLANNING_ASSUME_SLOW_LINK = 0x1;
const RSOP_PLANNING_ASSUME_LOOPBACK_MERGE = 0x2;
const RSOP_PLANNING_ASSUME_LOOPBACK_REPLACE = 0x4;
const RSOP_PLANNING_ASSUME_USER_WQLFILTER_TRUE = 0x8;
const RSOP_PLANNING_ASSUME_COMP_WQLFILTER_TRUE = 0x10;
const PI_NOUI = 0x1;
const PI_APPLYPOLICY = 0x2;
const PT_TEMPORARY = 0x1;
const PT_ROAMING = 0x2;
const PT_MANDATORY = 0x4;
const PT_ROAMING_PREEXISTING = 0x8;
const RP_FORCE = 0x1;
const RP_SYNC = 0x2;
const GPC_BLOCK_POLICY = 0x1;
const GPO_FLAG_DISABLE = 0x1;
const GPO_FLAG_FORCE = 0x2;
const GPO_LIST_FLAG_MACHINE = 0x1;
const GPO_LIST_FLAG_SITEONLY = 0x2;
const GPO_LIST_FLAG_NO_WMIFILTERS = 0x4;
const GPO_LIST_FLAG_NO_SECURITYFILTERS = 0x8;
const GPO_INFO_FLAG_MACHINE = 0x1;
const GPO_INFO_FLAG_BACKGROUND = 0x10;
const GPO_INFO_FLAG_SLOWLINK = 0x20;
const GPO_INFO_FLAG_VERBOSE = 0x40;
const GPO_INFO_FLAG_NOCHANGES = 0x80;
const GPO_INFO_FLAG_LINKTRANSITION = 0x100;
const GPO_INFO_FLAG_LOGRSOP_TRANSITION = 0x200;
const GPO_INFO_FLAG_FORCED_REFRESH = 0x400;
const GPO_INFO_FLAG_SAFEMODE_BOOT = 0x800;
const GPO_INFO_FLAG_ASYNC_FOREGROUND = 0x1000;
const FLAG_NO_GPO_FILTER = 0x80000000;
const FLAG_NO_CSE_INVOKE = 0x40000000;
const FLAG_ASSUME_SLOW_LINK = 0x20000000;
const FLAG_LOOPBACK_MERGE = 0x10000000;
const FLAG_LOOPBACK_REPLACE = 0x8000000;
const FLAG_ASSUME_USER_WQLFILTER_TRUE = 0x4000000;
const FLAG_ASSUME_COMP_WQLFILTER_TRUE = 0x2000000;
const FLAG_PLANNING_MODE = 0x1000000;
const FLAG_NO_USER = 0x1;
const FLAG_NO_COMPUTER = 0x2;
const FLAG_FORCE_CREATENAMESPACE = 0x4;
const RSOP_USER_ACCESS_DENIED = 0x1;
const RSOP_COMPUTER_ACCESS_DENIED = 0x2;
const RSOP_TEMPNAMESPACE_EXISTS = 0x4;
const LOCALSTATE_ASSIGNED = 0x1;
const LOCALSTATE_PUBLISHED = 0x2;
const LOCALSTATE_UNINSTALL_UNMANAGED = 0x4;
const LOCALSTATE_POLICYREMOVE_ORPHAN = 0x8;
const LOCALSTATE_POLICYREMOVE_UNINSTALL = 0x10;
const LOCALSTATE_ORPHANED = 0x20;
const LOCALSTATE_UNINSTALLED = 0x40;
const MANAGED_APPS_USERAPPLICATIONS = 0x1;
const MANAGED_APPS_FROMCATEGORY = 0x2;
const MANAGED_APPS_INFOLEVEL_DEFAULT = 0x10000;
const MANAGED_APPTYPE_WINDOWSINSTALLER = 0x1;
const MANAGED_APPTYPE_SETUPEXE = 0x2;
const MANAGED_APPTYPE_UNSUPPORTED = 0x3;
const CLSID_GPESnapIn = 0x0;
const NODEID_Machine = 0x0;
const NODEID_MachineSWSettings = 0x0;
const NODEID_User = 0x0;
const NODEID_UserSWSettings = 0x0;
const CLSID_GroupPolicyObject = 0x0;
const CLSID_RSOPSnapIn = 0x0;
const NODEID_RSOPMachine = 0x0;
const NODEID_RSOPMachineSWSettings = 0x0;
const NODEID_RSOPUser = 0x0;
const NODEID_RSOPUserSWSettings = 0x0;
const GPO_SECTION_ROOT = 0x0;
const GPO_SECTION_USER = 0x1;
const GPO_SECTION_MACHINE = 0x2;
const GPO_OPEN_LOAD_REGISTRY = 0x1;
const GPO_OPEN_READ_ONLY = 0x2;
const GPO_OPTION_DISABLE_USER = 0x1;
const GPO_OPTION_DISABLE_MACHINE = 0x2;
const RSOP_INFO_FLAG_DIAGNOSTIC_MODE = 0x1;
const GPO_BROWSE_DISABLENEW = 0x1;
const GPO_BROWSE_NOCOMPUTERS = 0x2;
const GPO_BROWSE_NODSGPOS = 0x4;
const GPO_BROWSE_OPENBUTTON = 0x8;
const GPO_BROWSE_INITTOALL = 0x10;
const GPO_BROWSE_NOUSERGPOS = 0x20;
const GPO_BROWSE_SENDAPPLYONEDIT = 0x40;
const GPMTemplate = '{ECF1D454-71DA-4E2F-A8C0-8185465911D9}';
