// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const MARSHALINTERFACE_MIN = 0x1f4;
const ASYNC_MODE_COMPATIBILITY = 0x1;
const ASYNC_MODE_DEFAULT = 0x0;
const STGTY_REPEAT = 0x100;
const STG_TOEND = 0xffffffff;
const STG_LAYOUT_SEQUENTIAL = 0x0;
const STG_LAYOUT_INTERLEAVED = 0x1;
const COM_RIGHTS_EXECUTE = 0x1;
const COM_RIGHTS_EXECUTE_LOCAL = 0x2;
const COM_RIGHTS_EXECUTE_REMOTE = 0x4;
const COM_RIGHTS_ACTIVATE_LOCAL = 0x8;
const COM_RIGHTS_ACTIVATE_REMOTE = 0x10;
const COM_RIGHTS_RESERVED1 = 0x20;
const COM_RIGHTS_RESERVED2 = 0x40;
const CWMO_MAX_HANDLES = 0x38;
const ROTREGFLAGS_ALLOWANYCLIENT = 0x1;
const APPIDREGFLAGS_ACTIVATE_IUSERVER_INDESKTOP = 0x1;
const APPIDREGFLAGS_SECURE_SERVER_PROCESS_SD_AND_BIND = 0x2;
const APPIDREGFLAGS_ISSUE_ACTIVATION_RPC_AT_IDENTIFY = 0x4;
const APPIDREGFLAGS_IUSERVER_UNMODIFIED_LOGON_TOKEN = 0x8;
const APPIDREGFLAGS_IUSERVER_SELF_SID_IN_LAUNCH_PERMISSION = 0x10;
const APPIDREGFLAGS_IUSERVER_ACTIVATE_IN_CLIENT_SESSION_ONLY = 0x20;
const APPIDREGFLAGS_RESERVED1 = 0x40;
const APPIDREGFLAGS_RESERVED2 = 0x80;
const APPIDREGFLAGS_RESERVED3 = 0x100;
const APPIDREGFLAGS_RESERVED4 = 0x200;
const APPIDREGFLAGS_RESERVED5 = 0x400;
const APPIDREGFLAGS_AAA_NO_IMPLICIT_ACTIVATE_AS_IU = 0x800;
const APPIDREGFLAGS_RESERVED7 = 0x1000;
const APPIDREGFLAGS_RESERVED8 = 0x2000;
const APPIDREGFLAGS_RESERVED9 = 0x4000;
const DCOMSCM_ACTIVATION_USE_ALL_AUTHNSERVICES = 0x1;
const DCOMSCM_ACTIVATION_DISALLOW_UNSECURE_CALL = 0x2;
const DCOMSCM_RESOLVE_USE_ALL_AUTHNSERVICES = 0x4;
const DCOMSCM_RESOLVE_DISALLOW_UNSECURE_CALL = 0x8;
const DCOMSCM_PING_USE_MID_AUTHNSERVICE = 0x10;
const DCOMSCM_PING_DISALLOW_UNSECURE_CALL = 0x20;
const MAXLSN = 0xffffffff;
const DMUS_ERRBASE = 0x1000;
