// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const SERVICE_ALL_ACCESS = 0xf01ff;
const SC_MANAGER_ALL_ACCESS = 0xf003f;
const SERVICE_NO_CHANGE = 0xffffffff;
const SERVICE_CONTROL_STOP = 0x1;
const SERVICE_CONTROL_PAUSE = 0x2;
const SERVICE_CONTROL_CONTINUE = 0x3;
const SERVICE_CONTROL_INTERROGATE = 0x4;
const SERVICE_CONTROL_SHUTDOWN = 0x5;
const SERVICE_CONTROL_PARAMCHANGE = 0x6;
const SERVICE_CONTROL_NETBINDADD = 0x7;
const SERVICE_CONTROL_NETBINDREMOVE = 0x8;
const SERVICE_CONTROL_NETBINDENABLE = 0x9;
const SERVICE_CONTROL_NETBINDDISABLE = 0xa;
const SERVICE_CONTROL_DEVICEEVENT = 0xb;
const SERVICE_CONTROL_HARDWAREPROFILECHANGE = 0xc;
const SERVICE_CONTROL_POWEREVENT = 0xd;
const SERVICE_CONTROL_SESSIONCHANGE = 0xe;
const SERVICE_CONTROL_PRESHUTDOWN = 0xf;
const SERVICE_CONTROL_TIMECHANGE = 0x10;
const SERVICE_CONTROL_TRIGGEREVENT = 0x20;
const SERVICE_CONTROL_LOWRESOURCES = 0x60;
const SERVICE_CONTROL_SYSTEMLOWRESOURCES = 0x61;
const SERVICE_ACCEPT_STOP = 0x1;
const SERVICE_ACCEPT_PAUSE_CONTINUE = 0x2;
const SERVICE_ACCEPT_SHUTDOWN = 0x4;
const SERVICE_ACCEPT_PARAMCHANGE = 0x8;
const SERVICE_ACCEPT_NETBINDCHANGE = 0x10;
const SERVICE_ACCEPT_HARDWAREPROFILECHANGE = 0x20;
const SERVICE_ACCEPT_POWEREVENT = 0x40;
const SERVICE_ACCEPT_SESSIONCHANGE = 0x80;
const SERVICE_ACCEPT_PRESHUTDOWN = 0x100;
const SERVICE_ACCEPT_TIMECHANGE = 0x200;
const SERVICE_ACCEPT_TRIGGEREVENT = 0x400;
const SERVICE_ACCEPT_USER_LOGOFF = 0x800;
const SERVICE_ACCEPT_LOWRESOURCES = 0x2000;
const SERVICE_ACCEPT_SYSTEMLOWRESOURCES = 0x4000;
const SC_MANAGER_CONNECT = 0x1;
const SC_MANAGER_CREATE_SERVICE = 0x2;
const SC_MANAGER_ENUMERATE_SERVICE = 0x4;
const SC_MANAGER_LOCK = 0x8;
const SC_MANAGER_QUERY_LOCK_STATUS = 0x10;
const SC_MANAGER_MODIFY_BOOT_CONFIG = 0x20;
const SERVICE_QUERY_CONFIG = 0x1;
const SERVICE_CHANGE_CONFIG = 0x2;
const SERVICE_QUERY_STATUS = 0x4;
const SERVICE_ENUMERATE_DEPENDENTS = 0x8;
const SERVICE_START = 0x10;
const SERVICE_STOP = 0x20;
const SERVICE_PAUSE_CONTINUE = 0x40;
const SERVICE_INTERROGATE = 0x80;
const SERVICE_USER_DEFINED_CONTROL = 0x100;
const SERVICE_NOTIFY_STATUS_CHANGE_1 = 0x1;
const SERVICE_NOTIFY_STATUS_CHANGE_2 = 0x2;
const SERVICE_NOTIFY_STATUS_CHANGE = 0x2;
const SERVICE_STOP_REASON_FLAG_MIN = 0x0;
const SERVICE_STOP_REASON_FLAG_UNPLANNED = 0x10000000;
const SERVICE_STOP_REASON_FLAG_CUSTOM = 0x20000000;
const SERVICE_STOP_REASON_FLAG_PLANNED = 0x40000000;
const SERVICE_STOP_REASON_FLAG_MAX = 0x80000000;
const SERVICE_STOP_REASON_MAJOR_MIN = 0x0;
const SERVICE_STOP_REASON_MAJOR_OTHER = 0x10000;
const SERVICE_STOP_REASON_MAJOR_HARDWARE = 0x20000;
const SERVICE_STOP_REASON_MAJOR_OPERATINGSYSTEM = 0x30000;
const SERVICE_STOP_REASON_MAJOR_SOFTWARE = 0x40000;
const SERVICE_STOP_REASON_MAJOR_APPLICATION = 0x50000;
const SERVICE_STOP_REASON_MAJOR_NONE = 0x60000;
const SERVICE_STOP_REASON_MAJOR_MAX = 0x70000;
const SERVICE_STOP_REASON_MAJOR_MIN_CUSTOM = 0x400000;
const SERVICE_STOP_REASON_MAJOR_MAX_CUSTOM = 0xff0000;
const SERVICE_STOP_REASON_MINOR_MIN = 0x0;
const SERVICE_STOP_REASON_MINOR_OTHER = 0x1;
const SERVICE_STOP_REASON_MINOR_MAINTENANCE = 0x2;
const SERVICE_STOP_REASON_MINOR_INSTALLATION = 0x3;
const SERVICE_STOP_REASON_MINOR_UPGRADE = 0x4;
const SERVICE_STOP_REASON_MINOR_RECONFIG = 0x5;
const SERVICE_STOP_REASON_MINOR_HUNG = 0x6;
const SERVICE_STOP_REASON_MINOR_UNSTABLE = 0x7;
const SERVICE_STOP_REASON_MINOR_DISK = 0x8;
const SERVICE_STOP_REASON_MINOR_NETWORKCARD = 0x9;
const SERVICE_STOP_REASON_MINOR_ENVIRONMENT = 0xa;
const SERVICE_STOP_REASON_MINOR_HARDWARE_DRIVER = 0xb;
const SERVICE_STOP_REASON_MINOR_OTHERDRIVER = 0xc;
const SERVICE_STOP_REASON_MINOR_SERVICEPACK = 0xd;
const SERVICE_STOP_REASON_MINOR_SOFTWARE_UPDATE = 0xe;
const SERVICE_STOP_REASON_MINOR_SECURITYFIX = 0xf;
const SERVICE_STOP_REASON_MINOR_SECURITY = 0x10;
const SERVICE_STOP_REASON_MINOR_NETWORK_CONNECTIVITY = 0x11;
const SERVICE_STOP_REASON_MINOR_WMI = 0x12;
const SERVICE_STOP_REASON_MINOR_SERVICEPACK_UNINSTALL = 0x13;
const SERVICE_STOP_REASON_MINOR_SOFTWARE_UPDATE_UNINSTALL = 0x14;
const SERVICE_STOP_REASON_MINOR_SECURITYFIX_UNINSTALL = 0x15;
const SERVICE_STOP_REASON_MINOR_MMC = 0x16;
const SERVICE_STOP_REASON_MINOR_NONE = 0x17;
const SERVICE_STOP_REASON_MINOR_MEMOTYLIMIT = 0x18;
const SERVICE_STOP_REASON_MINOR_MAX = 0x19;
const SERVICE_STOP_REASON_MINOR_MIN_CUSTOM = 0x100;
const SERVICE_STOP_REASON_MINOR_MAX_CUSTOM = 0xffff;
const SERVICE_CONTROL_STATUS_REASON_INFO = 0x1;
const SERVICE_SID_TYPE_NONE = 0x0;
const SERVICE_SID_TYPE_UNRESTRICTED = 0x1;
const SERVICE_TRIGGER_TYPE_CUSTOM_SYSTEM_STATE_CHANGE = 0x7;
const SERVICE_TRIGGER_TYPE_AGGREGATE = 0x1e;
const SERVICE_START_REASON_DEMAND = 0x1;
const SERVICE_START_REASON_AUTO = 0x2;
const SERVICE_START_REASON_TRIGGER = 0x4;
const SERVICE_START_REASON_RESTART_ON_FAILURE = 0x8;
const SERVICE_START_REASON_DELAYEDAUTO = 0x10;
const SERVICE_DYNAMIC_INFORMATION_LEVEL_START_REASON = 0x1;
const SERVICE_LAUNCH_PROTECTED_NONE = 0x0;
const SERVICE_LAUNCH_PROTECTED_WINDOWS = 0x1;
const SERVICE_LAUNCH_PROTECTED_WINDOWS_LIGHT = 0x2;
const SERVICE_LAUNCH_PROTECTED_ANTIMALWARE_LIGHT = 0x3;
const NETWORK_MANAGER_FIRST_IP_ADDRESS_ARRIVAL_GUID = 0x0;
const NETWORK_MANAGER_LAST_IP_ADDRESS_REMOVAL_GUID = 0x0;
const DOMAIN_JOIN_GUID = 0x0;
const DOMAIN_LEAVE_GUID = 0x0;
const FIREWALL_PORT_OPEN_GUID = 0x0;
const FIREWALL_PORT_CLOSE_GUID = 0x0;
const MACHINE_POLICY_PRESENT_GUID = 0x0;
const USER_POLICY_PRESENT_GUID = 0x0;
const RPC_INTERFACE_EVENT_GUID = 0x0;
const NAMED_PIPE_EVENT_GUID = 0x0;
const CUSTOM_SYSTEM_STATE_CHANGE_EVENT_GUID = 0x0;
