// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const WEBAUTHN_API_VERSION_1 = 0x1;
const WEBAUTHN_API_VERSION_2 = 0x2;
const WEBAUTHN_API_VERSION_3 = 0x3;
const WEBAUTHN_API_CURRENT_VERSION = 0x3;
const WEBAUTHN_RP_ENTITY_INFORMATION_CURRENT_VERSION = 0x1;
const WEBAUTHN_MAX_USER_ID_LENGTH = 0x40;
const WEBAUTHN_USER_ENTITY_INFORMATION_CURRENT_VERSION = 0x1;
const WEBAUTHN_CLIENT_DATA_CURRENT_VERSION = 0x1;
const WEBAUTHN_COSE_ALGORITHM_ECDSA_P256_WITH_SHA256 = 0xfffffff9;
const WEBAUTHN_COSE_ALGORITHM_ECDSA_P384_WITH_SHA384 = 0xffffffdd;
const WEBAUTHN_COSE_ALGORITHM_ECDSA_P521_WITH_SHA512 = 0xffffffdc;
const WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA256 = 0xfffffeff;
const WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA384 = 0xfffffefe;
const WEBAUTHN_COSE_ALGORITHM_RSASSA_PKCS1_V1_5_WITH_SHA512 = 0xfffffefd;
const WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA256 = 0xffffffdb;
const WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA384 = 0xffffffda;
const WEBAUTHN_COSE_ALGORITHM_RSA_PSS_WITH_SHA512 = 0xffffffd9;
const WEBAUTHN_COSE_CREDENTIAL_PARAMETER_CURRENT_VERSION = 0x1;
const WEBAUTHN_CREDENTIAL_CURRENT_VERSION = 0x1;
const WEBAUTHN_CTAP_TRANSPORT_USB = 0x1;
const WEBAUTHN_CTAP_TRANSPORT_NFC = 0x2;
const WEBAUTHN_CTAP_TRANSPORT_BLE = 0x4;
const WEBAUTHN_CTAP_TRANSPORT_TEST = 0x8;
const WEBAUTHN_CTAP_TRANSPORT_INTERNAL = 0x10;
const WEBAUTHN_CTAP_TRANSPORT_FLAGS_MASK = 0x1f;
const WEBAUTHN_CREDENTIAL_EX_CURRENT_VERSION = 0x1;
const WEBAUTHN_USER_VERIFICATION_ANY = 0x0;
const WEBAUTHN_USER_VERIFICATION_OPTIONAL = 0x1;
const WEBAUTHN_USER_VERIFICATION_OPTIONAL_WITH_CREDENTIAL_ID_LIST = 0x2;
const WEBAUTHN_USER_VERIFICATION_REQUIRED = 0x3;
const WEBAUTHN_AUTHENTICATOR_ATTACHMENT_ANY = 0x0;
const WEBAUTHN_AUTHENTICATOR_ATTACHMENT_PLATFORM = 0x1;
const WEBAUTHN_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM = 0x2;
const WEBAUTHN_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM_U2F_V2 = 0x3;
const WEBAUTHN_USER_VERIFICATION_REQUIREMENT_ANY = 0x0;
const WEBAUTHN_USER_VERIFICATION_REQUIREMENT_REQUIRED = 0x1;
const WEBAUTHN_USER_VERIFICATION_REQUIREMENT_PREFERRED = 0x2;
const WEBAUTHN_USER_VERIFICATION_REQUIREMENT_DISCOURAGED = 0x3;
const WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_ANY = 0x0;
const WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_NONE = 0x1;
const WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_INDIRECT = 0x2;
const WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT = 0x3;
const WEBAUTHN_ENTERPRISE_ATTESTATION_NONE = 0x0;
const WEBAUTHN_ENTERPRISE_ATTESTATION_VENDOR_FACILITATED = 0x1;
const WEBAUTHN_ENTERPRISE_ATTESTATION_PLATFORM_MANAGED = 0x2;
const WEBAUTHN_LARGE_BLOB_SUPPORT_NONE = 0x0;
const WEBAUTHN_LARGE_BLOB_SUPPORT_REQUIRED = 0x1;
const WEBAUTHN_LARGE_BLOB_SUPPORT_PREFERRED = 0x2;
const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_1 = 0x1;
const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_2 = 0x2;
const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_3 = 0x3;
const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_4 = 0x4;
const WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_CURRENT_VERSION = 0x4;
const WEBAUTHN_CRED_LARGE_BLOB_OPERATION_NONE = 0x0;
const WEBAUTHN_CRED_LARGE_BLOB_OPERATION_GET = 0x1;
const WEBAUTHN_CRED_LARGE_BLOB_OPERATION_SET = 0x2;
const WEBAUTHN_CRED_LARGE_BLOB_OPERATION_DELETE = 0x3;
const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_1 = 0x1;
const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_2 = 0x2;
const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_3 = 0x3;
const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_4 = 0x4;
const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_5 = 0x5;
const WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_CURRENT_VERSION = 0x5;
const WEBAUTHN_ATTESTATION_DECODE_NONE = 0x0;
const WEBAUTHN_ATTESTATION_DECODE_COMMON = 0x1;
const WEBAUTHN_COMMON_ATTESTATION_CURRENT_VERSION = 0x1;
const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_1 = 0x1;
const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_2 = 0x2;
const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_3 = 0x3;
const WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_4 = 0x4;
const WEBAUTHN_CREDENTIAL_ATTESTATION_CURRENT_VERSION = 0x4;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_NONE = 0x0;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_SUCCESS = 0x1;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_NOT_SUPPORTED = 0x2;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_INVALID_DATA = 0x3;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_INVALID_PARAMETER = 0x4;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_NOT_FOUND = 0x5;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_MULTIPLE_CREDENTIALS = 0x6;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_LACK_OF_SPACE = 0x7;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_PLATFORM_ERROR = 0x8;
const WEBAUTHN_CRED_LARGE_BLOB_STATUS_AUTHENTICATOR_ERROR = 0x9;
const WEBAUTHN_ASSERTION_VERSION_1 = 0x1;
const WEBAUTHN_ASSERTION_VERSION_2 = 0x2;
const WEBAUTHN_ASSERTION_CURRENT_VERSION = 0x2;
const WS_HTTP_HEADER_MAPPING_COMMA_SEPARATOR = 0x1;
const WS_HTTP_HEADER_MAPPING_SEMICOLON_SEPARATOR = 0x2;
const WS_HTTP_HEADER_MAPPING_QUOTED_VALUE = 0x4;
const WS_HTTP_RESPONSE_MAPPING_STATUS_CODE = 0x1;
const WS_HTTP_RESPONSE_MAPPING_STATUS_TEXT = 0x2;
const WS_HTTP_REQUEST_MAPPING_VERB = 0x2;
const WS_MATCH_URL_DNS_HOST = 0x1;
const WS_MATCH_URL_DNS_FULLY_QUALIFIED_HOST = 0x2;
const WS_MATCH_URL_NETBIOS_HOST = 0x4;
const WS_MATCH_URL_LOCAL_HOST = 0x8;
const WS_MATCH_URL_HOST_ADDRESSES = 0x10;
const WS_MATCH_URL_THIS_HOST = 0x1f;
const WS_MATCH_URL_PORT = 0x20;
const WS_MATCH_URL_EXACT_PATH = 0x40;
const WS_MATCH_URL_PREFIX_PATH = 0x80;
const WS_MATCH_URL_NO_QUERY = 0x100;
const WS_MUST_UNDERSTAND_HEADER_ATTRIBUTE = 0x1;
const WS_RELAY_HEADER_ATTRIBUTE = 0x2;
const WS_HTTP_HEADER_AUTH_SCHEME_NONE = 0x1;
const WS_HTTP_HEADER_AUTH_SCHEME_BASIC = 0x2;
const WS_HTTP_HEADER_AUTH_SCHEME_DIGEST = 0x4;
const WS_HTTP_HEADER_AUTH_SCHEME_NTLM = 0x8;
const WS_HTTP_HEADER_AUTH_SCHEME_NEGOTIATE = 0x10;
const WS_HTTP_HEADER_AUTH_SCHEME_PASSPORT = 0x20;
const WS_CERT_FAILURE_CN_MISMATCH = 0x1;
const WS_CERT_FAILURE_INVALID_DATE = 0x2;
const WS_CERT_FAILURE_UNTRUSTED_ROOT = 0x4;
const WS_CERT_FAILURE_WRONG_USAGE = 0x8;
const WS_CERT_FAILURE_REVOCATION_OFFLINE = 0x10;
const WS_STRUCT_ABSTRACT = 0x1;
const WS_STRUCT_IGNORE_TRAILING_ELEMENT_CONTENT = 0x2;
const WS_STRUCT_IGNORE_UNHANDLED_ATTRIBUTES = 0x4;
const WS_FIELD_POINTER = 0x1;
const WS_FIELD_OPTIONAL = 0x2;
const WS_FIELD_NILLABLE = 0x4;
const WS_FIELD_NILLABLE_ITEM = 0x8;
const WS_FIELD_OTHER_NAMESPACE = 0x10;
const WS_SERVICE_OPERATION_MESSAGE_NILLABLE_ELEMENT = 0x1;
const WS_URL_FLAGS_ALLOW_HOST_WILDCARDS = 0x1;
const WS_URL_FLAGS_NO_PATH_COLLAPSE = 0x2;
const WS_URL_FLAGS_ZERO_TERMINATE = 0x4;
