// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const SDDL_REVISION_1 = 0x1;
const SDDL_REVISION = 0x1;
const SDDL_ALIAS_SIZE = 0x2;
const INHERITED_ACCESS_ENTRY = 0x10;
const INHERITED_PARENT = 0x10000000;
const INHERITED_GRANDPARENT = 0x20000000;
const TRUSTEE_ACCESS_ALLOWED = 0x1;
const TRUSTEE_ACCESS_READ = 0x2;
const TRUSTEE_ACCESS_WRITE = 0x4;
const TRUSTEE_ACCESS_EXPLICIT = 0x1;
const TRUSTEE_ACCESS_ALL = 0xffffffff;
const ACTRL_RESERVED = 0x0;
const ACTRL_PERM_1 = 0x1;
const ACTRL_PERM_2 = 0x2;
const ACTRL_PERM_3 = 0x4;
const ACTRL_PERM_4 = 0x8;
const ACTRL_PERM_5 = 0x10;
const ACTRL_PERM_6 = 0x20;
const ACTRL_PERM_7 = 0x40;
const ACTRL_PERM_8 = 0x80;
const ACTRL_PERM_9 = 0x100;
const ACTRL_PERM_10 = 0x200;
const ACTRL_PERM_11 = 0x400;
const ACTRL_PERM_12 = 0x800;
const ACTRL_PERM_13 = 0x1000;
const ACTRL_PERM_14 = 0x2000;
const ACTRL_PERM_15 = 0x4000;
const ACTRL_PERM_16 = 0x8000;
const ACTRL_PERM_17 = 0x10000;
const ACTRL_PERM_18 = 0x20000;
const ACTRL_PERM_19 = 0x40000;
const ACTRL_PERM_20 = 0x80000;
const ACTRL_ACCESS_PROTECTED = 0x1;
const ACTRL_SYSTEM_ACCESS = 0x4000000;
const ACTRL_DELETE = 0x8000000;
const ACTRL_READ_CONTROL = 0x10000000;
const ACTRL_CHANGE_ACCESS = 0x20000000;
const ACTRL_CHANGE_OWNER = 0x40000000;
const ACTRL_SYNCHRONIZE = 0x80000000;
const ACTRL_STD_RIGHTS_ALL = 0xf8000000;
const ACTRL_FILE_READ = 0x1;
const ACTRL_FILE_WRITE = 0x2;
const ACTRL_FILE_APPEND = 0x4;
const ACTRL_FILE_READ_PROP = 0x8;
const ACTRL_FILE_WRITE_PROP = 0x10;
const ACTRL_FILE_EXECUTE = 0x20;
const ACTRL_FILE_READ_ATTRIB = 0x80;
const ACTRL_FILE_WRITE_ATTRIB = 0x100;
const ACTRL_FILE_CREATE_PIPE = 0x200;
const ACTRL_DIR_LIST = 0x1;
const ACTRL_DIR_CREATE_OBJECT = 0x2;
const ACTRL_DIR_CREATE_CHILD = 0x4;
const ACTRL_DIR_DELETE_CHILD = 0x40;
const ACTRL_DIR_TRAVERSE = 0x20;
const ACTRL_KERNEL_TERMINATE = 0x1;
const ACTRL_KERNEL_THREAD = 0x2;
const ACTRL_KERNEL_VM = 0x4;
const ACTRL_KERNEL_VM_READ = 0x8;
const ACTRL_KERNEL_VM_WRITE = 0x10;
const ACTRL_KERNEL_DUP_HANDLE = 0x20;
const ACTRL_KERNEL_PROCESS = 0x40;
const ACTRL_KERNEL_SET_INFO = 0x80;
const ACTRL_KERNEL_GET_INFO = 0x100;
const ACTRL_KERNEL_CONTROL = 0x200;
const ACTRL_KERNEL_ALERT = 0x400;
const ACTRL_KERNEL_GET_CONTEXT = 0x800;
const ACTRL_KERNEL_SET_CONTEXT = 0x1000;
const ACTRL_KERNEL_TOKEN = 0x2000;
const ACTRL_KERNEL_IMPERSONATE = 0x4000;
const ACTRL_KERNEL_DIMPERSONATE = 0x8000;
const ACTRL_PRINT_SADMIN = 0x1;
const ACTRL_PRINT_SLIST = 0x2;
const ACTRL_PRINT_PADMIN = 0x4;
const ACTRL_PRINT_PUSE = 0x8;
const ACTRL_PRINT_JADMIN = 0x10;
const ACTRL_SVC_GET_INFO = 0x1;
const ACTRL_SVC_SET_INFO = 0x2;
const ACTRL_SVC_STATUS = 0x4;
const ACTRL_SVC_LIST = 0x8;
const ACTRL_SVC_START = 0x10;
const ACTRL_SVC_STOP = 0x20;
const ACTRL_SVC_PAUSE = 0x40;
const ACTRL_SVC_INTERROGATE = 0x80;
const ACTRL_SVC_UCONTROL = 0x100;
const ACTRL_REG_QUERY = 0x1;
const ACTRL_REG_SET = 0x2;
const ACTRL_REG_CREATE_CHILD = 0x4;
const ACTRL_REG_LIST = 0x8;
const ACTRL_REG_NOTIFY = 0x10;
const ACTRL_REG_LINK = 0x20;
const ACTRL_WIN_CLIPBRD = 0x1;
const ACTRL_WIN_GLOBAL_ATOMS = 0x2;
const ACTRL_WIN_CREATE = 0x4;
const ACTRL_WIN_LIST_DESK = 0x8;
const ACTRL_WIN_LIST = 0x10;
const ACTRL_WIN_READ_ATTRIBS = 0x20;
const ACTRL_WIN_WRITE_ATTRIBS = 0x40;
const ACTRL_WIN_SCREEN = 0x80;
const ACTRL_WIN_EXIT = 0x100;
const ACTRL_ACCESS_NO_OPTIONS = 0x0;
const ACTRL_ACCESS_SUPPORTS_OBJECT_ENTRIES = 0x1;
const AUDIT_TYPE_LEGACY = 0x1;
const AUDIT_TYPE_WMI = 0x2;
const AP_ParamTypeBits = 0x8;
const AP_ParamTypeMask = 0xff;
const AUTHZ_SS_MAXSIZE = 0x80;
const APF_AuditFailure = 0x0;
const APF_AuditSuccess = 0x1;
const APF_ValidFlags = 0x1;
const AUTHZP_WPD_EVENT = 0x10;
const AUTHZ_ALLOW_MULTIPLE_SOURCE_INSTANCES = 0x1;
const AUTHZ_MIGRATED_LEGACY_PUBLISHER = 0x2;
const AUTHZ_AUDIT_INSTANCE_INFORMATION = 0x2;
const AUTHZ_SKIP_TOKEN_GROUPS = 0x2;
const AUTHZ_REQUIRE_S4U_LOGON = 0x4;
const AUTHZ_COMPUTE_PRIVILEGES = 0x8;
const AUTHZ_SECURITY_ATTRIBUTE_TYPE_INVALID = 0x0;
const AUTHZ_SECURITY_ATTRIBUTE_TYPE_INT64 = 0x1;
const AUTHZ_SECURITY_ATTRIBUTE_TYPE_UINT64 = 0x2;
const AUTHZ_SECURITY_ATTRIBUTE_TYPE_STRING = 0x3;
const AUTHZ_SECURITY_ATTRIBUTE_TYPE_FQBN = 0x4;
const AUTHZ_SECURITY_ATTRIBUTE_TYPE_SID = 0x5;
const AUTHZ_SECURITY_ATTRIBUTE_TYPE_BOOLEAN = 0x6;
const AUTHZ_SECURITY_ATTRIBUTE_TYPE_OCTET_STRING = 0x10;
const AUTHZ_SECURITY_ATTRIBUTES_INFORMATION_VERSION_V1 = 0x1;
const AUTHZ_SECURITY_ATTRIBUTES_INFORMATION_VERSION = 0x1;
const AUTHZ_RPC_INIT_INFO_CLIENT_VERSION_V1 = 0x1;
const AUTHZ_INIT_INFO_VERSION_V1 = 0x1;
const AUTHZ_WPD_CATEGORY_FLAG = 0x10;
const AUTHZ_FLAG_ALLOW_MULTIPLE_SOURCE_INSTANCES = 0x1;
const OLESCRIPT_E_SYNTAX = 0x80020101;
