/// {@category Enum}
class DCOMPOSITION_BACKFACE_VISIBILITY {
  static const DCOMPOSITION_BACKFACE_VISIBILITY_VISIBLE = 0x00000000;
  static const DCOMPOSITION_BACKFACE_VISIBILITY_HIDDEN = 0x00000001;
  static const DCOMPOSITION_BACKFACE_VISIBILITY_INHERIT = 0xffffffff;
}

/// {@category Enum}
class DCOMPOSITION_BITMAP_INTERPOLATION_MODE {
  static const DCOMPOSITION_BITMAP_INTERPOLATION_MODE_NEAREST_NEIGHBOR = 0x00000000;
  static const DCOMPOSITION_BITMAP_INTERPOLATION_MODE_LINEAR = 0x00000001;
  static const DCOMPOSITION_BITMAP_INTERPOLATION_MODE_INHERIT = 0xffffffff;
}

/// {@category Enum}
class DCOMPOSITION_BORDER_MODE {
  static const DCOMPOSITION_BORDER_MODE_SOFT = 0x00000000;
  static const DCOMPOSITION_BORDER_MODE_HARD = 0x00000001;
  static const DCOMPOSITION_BORDER_MODE_INHERIT = 0xffffffff;
}

/// {@category Enum}
class DCOMPOSITION_COMPOSITE_MODE {
  static const DCOMPOSITION_COMPOSITE_MODE_SOURCE_OVER = 0x00000000;
  static const DCOMPOSITION_COMPOSITE_MODE_DESTINATION_INVERT = 0x00000001;
  static const DCOMPOSITION_COMPOSITE_MODE_MIN_BLEND = 0x00000002;
  static const DCOMPOSITION_COMPOSITE_MODE_INHERIT = 0xffffffff;
}

/// {@category Enum}
class DCOMPOSITION_DEPTH_MODE {
  static const DCOMPOSITION_DEPTH_MODE_TREE = 0x00000000;
  static const DCOMPOSITION_DEPTH_MODE_SPATIAL = 0x00000001;
  static const DCOMPOSITION_DEPTH_MODE_SORTED = 0x00000003;
  static const DCOMPOSITION_DEPTH_MODE_INHERIT = 0xffffffff;
}

/// {@category Enum}
class DCOMPOSITION_OPACITY_MODE {
  static const DCOMPOSITION_OPACITY_MODE_LAYER = 0x00000000;
  static const DCOMPOSITION_OPACITY_MODE_MULTIPLY = 0x00000001;
  static const DCOMPOSITION_OPACITY_MODE_INHERIT = 0xffffffff;
}

