// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const OFFLINEFILES_SYNC_STATE_LOCAL_KNOWN = 0x1;
const OFFLINEFILES_SYNC_STATE_REMOTE_KNOWN = 0x2;
const OFFLINEFILES_CHANGES_NONE = 0x0;
const OFFLINEFILES_CHANGES_LOCAL_SIZE = 0x1;
const OFFLINEFILES_CHANGES_LOCAL_ATTRIBUTES = 0x2;
const OFFLINEFILES_CHANGES_LOCAL_TIME = 0x4;
const OFFLINEFILES_CHANGES_REMOTE_SIZE = 0x8;
const OFFLINEFILES_CHANGES_REMOTE_ATTRIBUTES = 0x10;
const OFFLINEFILES_CHANGES_REMOTE_TIME = 0x20;
const OFFLINEFILES_ITEM_FILTER_FLAG_MODIFIED_DATA = 0x1;
const OFFLINEFILES_ITEM_FILTER_FLAG_MODIFIED_ATTRIBUTES = 0x2;
const OFFLINEFILES_ITEM_FILTER_FLAG_MODIFIED = 0x4;
const OFFLINEFILES_ITEM_FILTER_FLAG_CREATED = 0x8;
const OFFLINEFILES_ITEM_FILTER_FLAG_DELETED = 0x10;
const OFFLINEFILES_ITEM_FILTER_FLAG_DIRTY = 0x20;
const OFFLINEFILES_ITEM_FILTER_FLAG_SPARSE = 0x40;
const OFFLINEFILES_ITEM_FILTER_FLAG_FILE = 0x80;
const OFFLINEFILES_ITEM_FILTER_FLAG_DIRECTORY = 0x100;
const OFFLINEFILES_ITEM_FILTER_FLAG_PINNED_USER = 0x200;
const OFFLINEFILES_ITEM_FILTER_FLAG_PINNED_OTHERS = 0x400;
const OFFLINEFILES_ITEM_FILTER_FLAG_PINNED_COMPUTER = 0x800;
const OFFLINEFILES_ITEM_FILTER_FLAG_PINNED = 0x1000;
const OFFLINEFILES_ITEM_FILTER_FLAG_GHOST = 0x2000;
const OFFLINEFILES_ITEM_FILTER_FLAG_SUSPENDED = 0x4000;
const OFFLINEFILES_ITEM_FILTER_FLAG_OFFLINE = 0x8000;
const OFFLINEFILES_ITEM_FILTER_FLAG_ONLINE = 0x10000;
const OFFLINEFILES_ITEM_FILTER_FLAG_USER_WRITE = 0x20000;
const OFFLINEFILES_ITEM_FILTER_FLAG_USER_READ = 0x40000;
const OFFLINEFILES_ITEM_FILTER_FLAG_USER_ANYACCESS = 0x80000;
const OFFLINEFILES_ITEM_FILTER_FLAG_OTHER_WRITE = 0x100000;
const OFFLINEFILES_ITEM_FILTER_FLAG_OTHER_READ = 0x200000;
const OFFLINEFILES_ITEM_FILTER_FLAG_OTHER_ANYACCESS = 0x400000;
const OFFLINEFILES_ITEM_FILTER_FLAG_GUEST_WRITE = 0x800000;
const OFFLINEFILES_ITEM_FILTER_FLAG_GUEST_READ = 0x1000000;
const OFFLINEFILES_ITEM_FILTER_FLAG_GUEST_ANYACCESS = 0x2000000;
const OFFLINEFILES_ITEM_QUERY_REMOTEINFO = 0x1;
const OFFLINEFILES_ITEM_QUERY_CONNECTIONSTATE = 0x2;
const OFFLINEFILES_ITEM_QUERY_LOCALDIRTYBYTECOUNT = 0x4;
const OFFLINEFILES_ITEM_QUERY_REMOTEDIRTYBYTECOUNT = 0x8;
const OFFLINEFILES_ITEM_QUERY_INCLUDETRANSPARENTCACHE = 0x10;
const OFFLINEFILES_ITEM_QUERY_ATTEMPT_TRANSITIONONLINE = 0x20;
const OFFLINEFILES_ITEM_QUERY_ADMIN = 0x80000000;
const OFFLINEFILES_ENUM_FLAT = 0x1;
const OFFLINEFILES_ENUM_FLAT_FILESONLY = 0x2;
const OFFLINEFILES_SETTING_SCOPE_USER = 0x1;
const OFFLINEFILES_SETTING_SCOPE_COMPUTER = 0x2;
const OFFLINEFILES_PINLINKTARGETS_NEVER = 0x0;
const OFFLINEFILES_PINLINKTARGETS_EXPLICIT = 0x1;
const OFFLINEFILES_PINLINKTARGETS_ALWAYS = 0x2;
const OFFLINEFILES_SYNC_CONTROL_FLAG_FILLSPARSE = 0x1;
const OFFLINEFILES_SYNC_CONTROL_FLAG_SYNCIN = 0x2;
const OFFLINEFILES_SYNC_CONTROL_FLAG_SYNCOUT = 0x4;
const OFFLINEFILES_SYNC_CONTROL_FLAG_PINNEWFILES = 0x8;
const OFFLINEFILES_SYNC_CONTROL_FLAG_PINLINKTARGETS = 0x10;
const OFFLINEFILES_SYNC_CONTROL_FLAG_PINFORUSER = 0x20;
const OFFLINEFILES_SYNC_CONTROL_FLAG_PINFORUSER_POLICY = 0x40;
const OFFLINEFILES_SYNC_CONTROL_FLAG_PINFORALL = 0x80;
const OFFLINEFILES_SYNC_CONTROL_FLAG_PINFORREDIR = 0x100;
const OFFLINEFILES_SYNC_CONTROL_FLAG_LOWPRIORITY = 0x200;
const OFFLINEFILES_SYNC_CONTROL_FLAG_ASYNCPROGRESS = 0x400;
const OFFLINEFILES_SYNC_CONTROL_FLAG_INTERACTIVE = 0x800;
const OFFLINEFILES_SYNC_CONTROL_FLAG_CONSOLE = 0x1000;
const OFFLINEFILES_SYNC_CONTROL_FLAG_SKIPSUSPENDEDDIRS = 0x2000;
const OFFLINEFILES_SYNC_CONTROL_FLAG_BACKGROUND = 0x10000;
const OFFLINEFILES_SYNC_CONTROL_FLAG_NONEWFILESOUT = 0x20000;
const OFFLINEFILES_SYNC_CONTROL_CR_MASK = 0xf0000000;
const OFFLINEFILES_SYNC_CONTROL_CR_DEFAULT = 0x0;
const OFFLINEFILES_SYNC_CONTROL_CR_KEEPLOCAL = 0x10000000;
const OFFLINEFILES_SYNC_CONTROL_CR_KEEPREMOTE = 0x20000000;
const OFFLINEFILES_SYNC_CONTROL_CR_KEEPLATEST = 0x30000000;
const OFFLINEFILES_PIN_CONTROL_FLAG_FORUSER = 0x20;
const OFFLINEFILES_PIN_CONTROL_FLAG_FORUSER_POLICY = 0x40;
const OFFLINEFILES_PIN_CONTROL_FLAG_FORALL = 0x80;
const OFFLINEFILES_PIN_CONTROL_FLAG_FORREDIR = 0x100;
const OFFLINEFILES_PIN_CONTROL_FLAG_FILL = 0x1;
const OFFLINEFILES_PIN_CONTROL_FLAG_LOWPRIORITY = 0x200;
const OFFLINEFILES_PIN_CONTROL_FLAG_ASYNCPROGRESS = 0x400;
const OFFLINEFILES_PIN_CONTROL_FLAG_INTERACTIVE = 0x800;
const OFFLINEFILES_PIN_CONTROL_FLAG_CONSOLE = 0x1000;
const OFFLINEFILES_PIN_CONTROL_FLAG_PINLINKTARGETS = 0x10;
const OFFLINEFILES_PIN_CONTROL_FLAG_BACKGROUND = 0x10000;
const OFFLINEFILES_ENCRYPTION_CONTROL_FLAG_LOWPRIORITY = 0x200;
const OFFLINEFILES_ENCRYPTION_CONTROL_FLAG_ASYNCPROGRESS = 0x400;
const OFFLINEFILES_ENCRYPTION_CONTROL_FLAG_INTERACTIVE = 0x800;
const OFFLINEFILES_ENCRYPTION_CONTROL_FLAG_CONSOLE = 0x1000;
const OFFLINEFILES_ENCRYPTION_CONTROL_FLAG_BACKGROUND = 0x10000;
const OFFLINEFILES_DELETE_FLAG_NOAUTOCACHED = 0x1;
const OFFLINEFILES_DELETE_FLAG_NOPINNED = 0x2;
const OFFLINEFILES_DELETE_FLAG_DELMODIFIED = 0x4;
const OFFLINEFILES_DELETE_FLAG_ADMIN = 0x80000000;
const OFFLINEFILES_TRANSITION_FLAG_INTERACTIVE = 0x1;
const OFFLINEFILES_TRANSITION_FLAG_CONSOLE = 0x2;
const OFFLINEFILES_SYNC_ITEM_CHANGE_NONE = 0x0;
const OFFLINEFILES_SYNC_ITEM_CHANGE_CHANGETIME = 0x1;
const OFFLINEFILES_SYNC_ITEM_CHANGE_WRITETIME = 0x2;
const OFFLINEFILES_SYNC_ITEM_CHANGE_FILESIZE = 0x4;
const OFFLINEFILES_SYNC_ITEM_CHANGE_ATTRIBUTES = 0x8;
