// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const WNGETCON_CONNECTED = 0x0;
const WNGETCON_DISCONNECTED = 0x1;
const WNNC_SPEC_VERSION = 0x1;
const WNNC_SPEC_VERSION51 = 0x50001;
const WNNC_NET_TYPE = 0x2;
const WNNC_NET_NONE = 0x0;
const WNNC_DRIVER_VERSION = 0x3;
const WNNC_USER = 0x4;
const WNNC_USR_GETUSER = 0x1;
const WNNC_CONNECTION = 0x6;
const WNNC_CON_ADDCONNECTION = 0x1;
const WNNC_CON_CANCELCONNECTION = 0x2;
const WNNC_CON_GETCONNECTIONS = 0x4;
const WNNC_CON_ADDCONNECTION3 = 0x8;
const WNNC_CON_ADDCONNECTION4 = 0x10;
const WNNC_CON_CANCELCONNECTION2 = 0x20;
const WNNC_CON_GETPERFORMANCE = 0x40;
const WNNC_CON_DEFER = 0x80;
const WNNC_DIALOG = 0x8;
const WNNC_DLG_DEVICEMODE = 0x1;
const WNNC_DLG_PROPERTYDIALOG = 0x20;
const WNNC_DLG_SEARCHDIALOG = 0x40;
const WNNC_DLG_FORMATNETWORKNAME = 0x80;
const WNNC_DLG_PERMISSIONEDITOR = 0x100;
const WNNC_DLG_GETRESOURCEPARENT = 0x200;
const WNNC_DLG_GETRESOURCEINFORMATION = 0x800;
const WNNC_ADMIN = 0x9;
const WNNC_ADM_GETDIRECTORYTYPE = 0x1;
const WNNC_ADM_DIRECTORYNOTIFY = 0x2;
const WNNC_ENUMERATION = 0xb;
const WNNC_ENUM_GLOBAL = 0x1;
const WNNC_ENUM_LOCAL = 0x2;
const WNNC_ENUM_CONTEXT = 0x4;
const WNNC_ENUM_SHAREABLE = 0x8;
const WNNC_START = 0xc;
const WNNC_WAIT_FOR_START = 0x1;
const WNNC_CONNECTION_FLAGS = 0xd;
const WNTYPE_DRIVE = 0x1;
const WNTYPE_FILE = 0x2;
const WNTYPE_PRINTER = 0x3;
const WNTYPE_COMM = 0x4;
const WNSRCH_REFRESH_FIRST_LEVEL = 0x1;
const WNDT_NORMAL = 0x0;
const WNDT_NETWORK = 0x1;
const WN_NETWORK_CLASS = 0x1;
const WN_CREDENTIAL_CLASS = 0x2;
const WN_PRIMARY_AUTHENT_CLASS = 0x4;
const WN_SERVICE_CLASS = 0x8;
const WN_VALID_LOGON_ACCOUNT = 0x1;
const WN_NT_PASSWORD_CHANGED = 0x2;
const NOTIFY_PRE = 0x1;
const NOTIFY_POST = 0x2;
const WNPERMC_PERM = 0x1;
const WNPERMC_AUDIT = 0x2;
const WNPERMC_OWNER = 0x4;
const RESOURCE_RECENT = 0x4;
const RESOURCETYPE_RESERVED = 0x8;
const RESOURCETYPE_UNKNOWN = 0xffffffff;
const RESOURCEUSAGE_NOLOCALDEVICE = 0x4;
const RESOURCEUSAGE_SIBLING = 0x8;
const RESOURCEUSAGE_RESERVED = 0x80000000;
const RESOURCEDISPLAYTYPE_NETWORK = 0x6;
const RESOURCEDISPLAYTYPE_ROOT = 0x7;
const RESOURCEDISPLAYTYPE_SHAREADMIN = 0x8;
const RESOURCEDISPLAYTYPE_DIRECTORY = 0x9;
const RESOURCEDISPLAYTYPE_NDSCONTAINER = 0xb;
const NETPROPERTY_PERSISTENT = 0x1;
const CONNECT_NEED_DRIVE = 0x20;
const CONNECT_REFCOUNT = 0x40;
const CONNECT_LOCALDRIVE = 0x100;
const CONNECT_CURRENT_MEDIA = 0x200;
const CONNECT_RESERVED = 0xff000000;
const CONNECT_CRED_RESET = 0x2000;
const CONNECT_REQUIRE_INTEGRITY = 0x4000;
const CONNECT_REQUIRE_PRIVACY = 0x8000;
const CONNECT_WRITE_THROUGH_SEMANTICS = 0x10000;
const CONNECT_GLOBAL_MAPPING = 0x40000;
const WNFMT_INENUM = 0x10;
const WNFMT_CONNECTION = 0x20;
const WNCON_FORNETCARD = 0x1;
const WNCON_NOTROUTED = 0x2;
const WNCON_SLOWLINK = 0x4;
const WNCON_DYNAMIC = 0x8;
