// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

import 'package:meta/meta.dart';

import '../guid.dart';
import '../types.dart';
import 'iaccessible.g.dart';
import 'iagileobject.g.dart';
import 'iapplicationactivationmanager.g.dart';
import 'iappxblockmapblock.g.dart';
import 'iappxblockmapblocksenumerator.g.dart';
import 'iappxblockmapfile.g.dart';
import 'iappxblockmapfilesenumerator.g.dart';
import 'iappxblockmapreader.g.dart';
import 'iappxfactory.g.dart';
import 'iappxfile.g.dart';
import 'iappxfilesenumerator.g.dart';
import 'iappxmanifestapplication.g.dart';
import 'iappxmanifestapplicationsenumerator.g.dart';
import 'iappxmanifestcapabilitiesenumerator.g.dart';
import 'iappxmanifestdevicecapabilitiesenumerator.g.dart';
import 'iappxmanifestdriverconstraint.g.dart';
import 'iappxmanifestdriverconstraintsenumerator.g.dart';
import 'iappxmanifestdriverdependenciesenumerator.g.dart';
import 'iappxmanifestdriverdependency.g.dart';
import 'iappxmanifesthostruntimedependenciesenumerator.g.dart';
import 'iappxmanifesthostruntimedependency.g.dart';
import 'iappxmanifesthostruntimedependency2.g.dart';
import 'iappxmanifestmainpackagedependenciesenumerator.g.dart';
import 'iappxmanifestmainpackagedependency.g.dart';
import 'iappxmanifestoptionalpackageinfo.g.dart';
import 'iappxmanifestospackagedependenciesenumerator.g.dart';
import 'iappxmanifestospackagedependency.g.dart';
import 'iappxmanifestpackagedependenciesenumerator.g.dart';
import 'iappxmanifestpackagedependency.g.dart';
import 'iappxmanifestpackageid.g.dart';
import 'iappxmanifestproperties.g.dart';
import 'iappxmanifestqualifiedresource.g.dart';
import 'iappxmanifestqualifiedresourcesenumerator.g.dart';
import 'iappxmanifestreader.g.dart';
import 'iappxmanifestreader2.g.dart';
import 'iappxmanifestreader3.g.dart';
import 'iappxmanifestreader4.g.dart';
import 'iappxmanifestreader5.g.dart';
import 'iappxmanifestreader6.g.dart';
import 'iappxmanifestreader7.g.dart';
import 'iappxmanifestresourcesenumerator.g.dart';
import 'iappxmanifesttargetdevicefamiliesenumerator.g.dart';
import 'iappxmanifesttargetdevicefamily.g.dart';
import 'iappxpackagereader.g.dart';
import 'iappxpackagewriter.g.dart';
import 'iaudiocaptureclient.g.dart';
import 'iaudioclient.g.dart';
import 'iaudioclient2.g.dart';
import 'iaudioclient3.g.dart';
import 'iaudioclientduckingcontrol.g.dart';
import 'iaudioclock.g.dart';
import 'iaudioclock2.g.dart';
import 'iaudioclockadjustment.g.dart';
import 'iaudiorenderclient.g.dart';
import 'iaudiosessioncontrol.g.dart';
import 'iaudiosessioncontrol2.g.dart';
import 'iaudiosessionenumerator.g.dart';
import 'iaudiosessionevents.g.dart';
import 'iaudiosessionmanager.g.dart';
import 'iaudiosessionmanager2.g.dart';
import 'iaudiosessionnotification.g.dart';
import 'iaudiostreamvolume.g.dart';
import 'iaudiovolumeducknotification.g.dart';
import 'ibindctx.g.dart';
import 'ichannelaudiovolume.g.dart';
import 'iclassfactory.g.dart';
import 'iconnectionpoint.g.dart';
import 'iconnectionpointcontainer.g.dart';
import 'id3d11asynchronous.g.dart';
import 'id3d11authenticatedchannel.g.dart';
import 'id3d11blendstate.g.dart';
import 'id3d11blendstate1.g.dart';
import 'id3d11buffer.g.dart';
import 'id3d11classinstance.g.dart';
import 'id3d11classlinkage.g.dart';
import 'id3d11commandlist.g.dart';
import 'id3d11computeshader.g.dart';
import 'id3d11counter.g.dart';
import 'id3d11cryptosession.g.dart';
import 'id3d11debug.g.dart';
import 'id3d11depthstencilstate.g.dart';
import 'id3d11depthstencilview.g.dart';
import 'id3d11device.g.dart';
import 'id3d11device1.g.dart';
import 'id3d11device2.g.dart';
import 'id3d11device3.g.dart';
import 'id3d11device4.g.dart';
import 'id3d11device5.g.dart';
import 'id3d11devicechild.g.dart';
import 'id3d11devicecontext.g.dart';
import 'id3d11devicecontext1.g.dart';
import 'id3d11devicecontext2.g.dart';
import 'id3d11devicecontext3.g.dart';
import 'id3d11devicecontext4.g.dart';
import 'id3d11domainshader.g.dart';
import 'id3d11fence.g.dart';
import 'id3d11functionlinkinggraph.g.dart';
import 'id3d11functionparameterreflection.g.dart';
import 'id3d11functionreflection.g.dart';
import 'id3d11geometryshader.g.dart';
import 'id3d11hullshader.g.dart';
import 'id3d11infoqueue.g.dart';
import 'id3d11inputlayout.g.dart';
import 'id3d11libraryreflection.g.dart';
import 'id3d11linker.g.dart';
import 'id3d11linkingnode.g.dart';
import 'id3d11module.g.dart';
import 'id3d11moduleinstance.g.dart';
import 'id3d11multithread.g.dart';
import 'id3d11pixelshader.g.dart';
import 'id3d11predicate.g.dart';
import 'id3d11query.g.dart';
import 'id3d11query1.g.dart';
import 'id3d11rasterizerstate.g.dart';
import 'id3d11rasterizerstate1.g.dart';
import 'id3d11rasterizerstate2.g.dart';
import 'id3d11refdefaulttrackingoptions.g.dart';
import 'id3d11reftrackingoptions.g.dart';
import 'id3d11rendertargetview.g.dart';
import 'id3d11rendertargetview1.g.dart';
import 'id3d11resource.g.dart';
import 'id3d11samplerstate.g.dart';
import 'id3d11shaderreflection.g.dart';
import 'id3d11shaderreflectionconstantbuffer.g.dart';
import 'id3d11shaderreflectiontype.g.dart';
import 'id3d11shaderreflectionvariable.g.dart';
import 'id3d11shaderresourceview.g.dart';
import 'id3d11shaderresourceview1.g.dart';
import 'id3d11shadertrace.g.dart';
import 'id3d11shadertracefactory.g.dart';
import 'id3d11switchtoref.g.dart';
import 'id3d11texture1d.g.dart';
import 'id3d11texture2d.g.dart';
import 'id3d11texture2d1.g.dart';
import 'id3d11texture3d.g.dart';
import 'id3d11texture3d1.g.dart';
import 'id3d11tracingdevice.g.dart';
import 'id3d11unorderedaccessview.g.dart';
import 'id3d11unorderedaccessview1.g.dart';
import 'id3d11vertexshader.g.dart';
import 'id3d11videocontext.g.dart';
import 'id3d11videocontext1.g.dart';
import 'id3d11videocontext2.g.dart';
import 'id3d11videocontext3.g.dart';
import 'id3d11videodecoder.g.dart';
import 'id3d11videodecoderoutputview.g.dart';
import 'id3d11videodevice.g.dart';
import 'id3d11videodevice1.g.dart';
import 'id3d11videodevice2.g.dart';
import 'id3d11videoprocessor.g.dart';
import 'id3d11videoprocessorenumerator.g.dart';
import 'id3d11videoprocessorenumerator1.g.dart';
import 'id3d11videoprocessorinputview.g.dart';
import 'id3d11videoprocessoroutputview.g.dart';
import 'id3d11view.g.dart';
import 'id3dblob.g.dart';
import 'id3ddevicecontextstate.g.dart';
import 'id3duserdefinedannotation.g.dart';
import 'id3dx11fft.g.dart';
import 'id3dx11scan.g.dart';
import 'id3dx11segmentedscan.g.dart';
import 'idcompositionaffinetransform2deffect.g.dart';
import 'idcompositionanimation.g.dart';
import 'idcompositionarithmeticcompositeeffect.g.dart';
import 'idcompositionblendeffect.g.dart';
import 'idcompositionbrightnesseffect.g.dart';
import 'idcompositionclip.g.dart';
import 'idcompositioncolormatrixeffect.g.dart';
import 'idcompositioncompositeeffect.g.dart';
import 'idcompositiondelegatedinktrail.g.dart';
import 'idcompositiondesktopdevice.g.dart';
import 'idcompositiondevice.g.dart';
import 'idcompositiondevice2.g.dart';
import 'idcompositiondevice3.g.dart';
import 'idcompositiondevice4.g.dart';
import 'idcompositiondevice5.g.dart';
import 'idcompositiondevicedebug.g.dart';
import 'idcompositiondynamictexture.g.dart';
import 'idcompositioneffect.g.dart';
import 'idcompositioneffectgroup.g.dart';
import 'idcompositionfiltereffect.g.dart';
import 'idcompositiongaussianblureffect.g.dart';
import 'idcompositionhuerotationeffect.g.dart';
import 'idcompositioninktraildevice.g.dart';
import 'idcompositionlineartransfereffect.g.dart';
import 'idcompositionmatrixtransform.g.dart';
import 'idcompositionmatrixtransform3d.g.dart';
import 'idcompositionrectangleclip.g.dart';
import 'idcompositionrotatetransform.g.dart';
import 'idcompositionrotatetransform3d.g.dart';
import 'idcompositionsaturationeffect.g.dart';
import 'idcompositionscaletransform.g.dart';
import 'idcompositionscaletransform3d.g.dart';
import 'idcompositionshadoweffect.g.dart';
import 'idcompositionskewtransform.g.dart';
import 'idcompositionsurface.g.dart';
import 'idcompositionsurfacefactory.g.dart';
import 'idcompositiontabletransfereffect.g.dart';
import 'idcompositiontarget.g.dart';
import 'idcompositiontexture.g.dart';
import 'idcompositiontransform.g.dart';
import 'idcompositiontransform3d.g.dart';
import 'idcompositiontranslatetransform.g.dart';
import 'idcompositiontranslatetransform3d.g.dart';
import 'idcompositionturbulenceeffect.g.dart';
import 'idcompositionvirtualsurface.g.dart';
import 'idcompositionvisual.g.dart';
import 'idcompositionvisual2.g.dart';
import 'idcompositionvisual3.g.dart';
import 'idcompositionvisualdebug.g.dart';
import 'idesktopwallpaper.g.dart';
import 'idispatch.g.dart';
import 'idxgiadapter.g.dart';
import 'idxgidevice.g.dart';
import 'idxgidevicesubobject.g.dart';
import 'idxgiobject.g.dart';
import 'idxgioutput.g.dart';
import 'idxgisurface.g.dart';
import 'idxgisurface1.g.dart';
import 'idxgiswapchain.g.dart';
import 'ienumconnectionpoints.g.dart';
import 'ienumconnections.g.dart';
import 'ienumidlist.g.dart';
import 'ienummoniker.g.dart';
import 'ienumnetworkconnections.g.dart';
import 'ienumnetworks.g.dart';
import 'ienumresources.g.dart';
import 'ienumshellitems.g.dart';
import 'ienumspellingerror.g.dart';
import 'ienumspobjecttokens.g.dart';
import 'ienumstatstg.g.dart';
import 'ienumstring.g.dart';
import 'ienumvariant.g.dart';
import 'ienumwbemclassobject.g.dart';
import 'ierrorinfo.g.dart';
import 'ifiledialog.g.dart';
import 'ifiledialog2.g.dart';
import 'ifiledialogcustomize.g.dart';
import 'ifiledialogevents.g.dart';
import 'ifileisinuse.g.dart';
import 'ifileopendialog.g.dart';
import 'ifileoperationprogresssink.g.dart';
import 'ifilesavedialog.g.dart';
import 'iinitializewithwindow.g.dart';
import 'iinspectable.g.dart';
import 'iknownfolder.g.dart';
import 'iknownfoldermanager.g.dart';
import 'imalloc.g.dart';
import 'imetadataassemblyimport.g.dart';
import 'imetadatadispenser.g.dart';
import 'imetadatadispenserex.g.dart';
import 'imetadataimport.g.dart';
import 'imetadataimport2.g.dart';
import 'imetadatatables.g.dart';
import 'imetadatatables2.g.dart';
import 'immdevice.g.dart';
import 'immdevicecollection.g.dart';
import 'immdeviceenumerator.g.dart';
import 'immendpoint.g.dart';
import 'immnotificationclient.g.dart';
import 'imodalwindow.g.dart';
import 'imoniker.g.dart';
import 'inetwork.g.dart';
import 'inetworkconnection.g.dart';
import 'inetworklistmanager.g.dart';
import 'inetworklistmanagerevents.g.dart';
import 'ioptiondescription.g.dart';
import 'ipersist.g.dart';
import 'ipersistfile.g.dart';
import 'ipersistmemory.g.dart';
import 'ipersiststream.g.dart';
import 'iportabledevicekeycollection.g.dart';
import 'iportabledevicepropvariantcollection.g.dart';
import 'iportabledevicevalues.g.dart';
import 'iportabledevicevaluescollection.g.dart';
import 'ipropertydescriptionlist.g.dart';
import 'ipropertystore.g.dart';
import 'iprovideclassinfo.g.dart';
import 'irawelementprovidersimple.g.dart';
import 'irecordinfo.g.dart';
import 'irestrictederrorinfo.g.dart';
import 'irunningobjecttable.g.dart';
import 'isensor.g.dart';
import 'isensorcollection.g.dart';
import 'isensordatareport.g.dart';
import 'isensorevents.g.dart';
import 'isensormanager.g.dart';
import 'isensormanagerevents.g.dart';
import 'isequentialstream.g.dart';
import 'ishellfolder.g.dart';
import 'ishellitem.g.dart';
import 'ishellitem2.g.dart';
import 'ishellitemarray.g.dart';
import 'ishellitemfilter.g.dart';
import 'ishellitemimagefactory.g.dart';
import 'ishellitemresources.g.dart';
import 'ishelllink.g.dart';
import 'ishelllinkdatalist.g.dart';
import 'ishelllinkdual.g.dart';
import 'ishellservice.g.dart';
import 'isimpleaudiovolume.g.dart';
import 'ispdatakey.g.dart';
import 'ispeechaudioformat.g.dart';
import 'ispeechbasestream.g.dart';
import 'ispeechdatakey.g.dart';
import 'ispeechobjecttoken.g.dart';
import 'ispeechobjecttokencategory.g.dart';
import 'ispeechobjecttokens.g.dart';
import 'ispeechvoice.g.dart';
import 'ispeechvoicestatus.g.dart';
import 'ispeechwaveformatex.g.dart';
import 'ispellchecker.g.dart';
import 'ispellchecker2.g.dart';
import 'ispellcheckerchangedeventhandler.g.dart';
import 'ispellcheckerfactory.g.dart';
import 'ispellingerror.g.dart';
import 'ispeventsource.g.dart';
import 'ispnotifysink.g.dart';
import 'ispnotifysource.g.dart';
import 'ispobjecttoken.g.dart';
import 'ispobjecttokencategory.g.dart';
import 'ispstreamformat.g.dart';
import 'ispvoice.g.dart';
import 'istorage.g.dart';
import 'istream.g.dart';
import 'isupporterrorinfo.g.dart';
import 'itypecomp.g.dart';
import 'itypeinfo.g.dart';
import 'itypelib.g.dart';
import 'iuiautomation.g.dart';
import 'iuiautomation2.g.dart';
import 'iuiautomation3.g.dart';
import 'iuiautomation4.g.dart';
import 'iuiautomation5.g.dart';
import 'iuiautomation6.g.dart';
import 'iuiautomationactivetextpositionchangedeventhandler.g.dart';
import 'iuiautomationandcondition.g.dart';
import 'iuiautomationannotationpattern.g.dart';
import 'iuiautomationboolcondition.g.dart';
import 'iuiautomationcacherequest.g.dart';
import 'iuiautomationchangeseventhandler.g.dart';
import 'iuiautomationcondition.g.dart';
import 'iuiautomationcustomnavigationpattern.g.dart';
import 'iuiautomationdockpattern.g.dart';
import 'iuiautomationdragpattern.g.dart';
import 'iuiautomationdroptargetpattern.g.dart';
import 'iuiautomationelement.g.dart';
import 'iuiautomationelement2.g.dart';
import 'iuiautomationelement3.g.dart';
import 'iuiautomationelement4.g.dart';
import 'iuiautomationelement5.g.dart';
import 'iuiautomationelement6.g.dart';
import 'iuiautomationelement7.g.dart';
import 'iuiautomationelement8.g.dart';
import 'iuiautomationelement9.g.dart';
import 'iuiautomationelementarray.g.dart';
import 'iuiautomationeventhandler.g.dart';
import 'iuiautomationeventhandlergroup.g.dart';
import 'iuiautomationexpandcollapsepattern.g.dart';
import 'iuiautomationfocuschangedeventhandler.g.dart';
import 'iuiautomationgriditempattern.g.dart';
import 'iuiautomationgridpattern.g.dart';
import 'iuiautomationinvokepattern.g.dart';
import 'iuiautomationitemcontainerpattern.g.dart';
import 'iuiautomationlegacyiaccessiblepattern.g.dart';
import 'iuiautomationmultipleviewpattern.g.dart';
import 'iuiautomationnotcondition.g.dart';
import 'iuiautomationnotificationeventhandler.g.dart';
import 'iuiautomationobjectmodelpattern.g.dart';
import 'iuiautomationorcondition.g.dart';
import 'iuiautomationpropertychangedeventhandler.g.dart';
import 'iuiautomationpropertycondition.g.dart';
import 'iuiautomationproxyfactory.g.dart';
import 'iuiautomationproxyfactoryentry.g.dart';
import 'iuiautomationproxyfactorymapping.g.dart';
import 'iuiautomationrangevaluepattern.g.dart';
import 'iuiautomationscrollitempattern.g.dart';
import 'iuiautomationscrollpattern.g.dart';
import 'iuiautomationselectionitempattern.g.dart';
import 'iuiautomationselectionpattern.g.dart';
import 'iuiautomationselectionpattern2.g.dart';
import 'iuiautomationspreadsheetitempattern.g.dart';
import 'iuiautomationspreadsheetpattern.g.dart';
import 'iuiautomationstructurechangedeventhandler.g.dart';
import 'iuiautomationstylespattern.g.dart';
import 'iuiautomationsynchronizedinputpattern.g.dart';
import 'iuiautomationtableitempattern.g.dart';
import 'iuiautomationtablepattern.g.dart';
import 'iuiautomationtextchildpattern.g.dart';
import 'iuiautomationtexteditpattern.g.dart';
import 'iuiautomationtextedittextchangedeventhandler.g.dart';
import 'iuiautomationtextpattern.g.dart';
import 'iuiautomationtextpattern2.g.dart';
import 'iuiautomationtextrange.g.dart';
import 'iuiautomationtextrange2.g.dart';
import 'iuiautomationtextrange3.g.dart';
import 'iuiautomationtextrangearray.g.dart';
import 'iuiautomationtogglepattern.g.dart';
import 'iuiautomationtransformpattern.g.dart';
import 'iuiautomationtransformpattern2.g.dart';
import 'iuiautomationtreewalker.g.dart';
import 'iuiautomationvaluepattern.g.dart';
import 'iuiautomationvirtualizeditempattern.g.dart';
import 'iuiautomationwindowpattern.g.dart';
import 'iunknown.g.dart';
import 'iuri.g.dart';
import 'ivirtualdesktopmanager.g.dart';
import 'iwbemcallresult.g.dart';
import 'iwbemclassobject.g.dart';
import 'iwbemconfigurerefresher.g.dart';
import 'iwbemcontext.g.dart';
import 'iwbemhiperfenum.g.dart';
import 'iwbemlocator.g.dart';
import 'iwbemobjectaccess.g.dart';
import 'iwbemobjectsink.g.dart';
import 'iwbemqualifierset.g.dart';
import 'iwbemrefresher.g.dart';
import 'iwbemservices.g.dart';
import 'iwebauthenticationcoremanagerinterop.g.dart';
import 'iwinhttprequest.g.dart';

part 'interface.dart';

const _predefinedCompanions = <Type, ComCompanion>{
  IAccessible: IAccessibleCompanion(),
  IAgileObject: IAgileObjectCompanion(),
  IApplicationActivationManager: IApplicationActivationManagerCompanion(),
  IAppxBlockMapBlock: IAppxBlockMapBlockCompanion(),
  IAppxBlockMapBlocksEnumerator: IAppxBlockMapBlocksEnumeratorCompanion(),
  IAppxBlockMapFile: IAppxBlockMapFileCompanion(),
  IAppxBlockMapFilesEnumerator: IAppxBlockMapFilesEnumeratorCompanion(),
  IAppxBlockMapReader: IAppxBlockMapReaderCompanion(),
  IAppxFactory: IAppxFactoryCompanion(),
  IAppxFile: IAppxFileCompanion(),
  IAppxFilesEnumerator: IAppxFilesEnumeratorCompanion(),
  IAppxManifestApplication: IAppxManifestApplicationCompanion(),
  IAppxManifestApplicationsEnumerator:
      IAppxManifestApplicationsEnumeratorCompanion(),
  IAppxManifestCapabilitiesEnumerator:
      IAppxManifestCapabilitiesEnumeratorCompanion(),
  IAppxManifestDeviceCapabilitiesEnumerator:
      IAppxManifestDeviceCapabilitiesEnumeratorCompanion(),
  IAppxManifestDriverConstraint: IAppxManifestDriverConstraintCompanion(),
  IAppxManifestDriverConstraintsEnumerator:
      IAppxManifestDriverConstraintsEnumeratorCompanion(),
  IAppxManifestDriverDependenciesEnumerator:
      IAppxManifestDriverDependenciesEnumeratorCompanion(),
  IAppxManifestDriverDependency: IAppxManifestDriverDependencyCompanion(),
  IAppxManifestHostRuntimeDependenciesEnumerator:
      IAppxManifestHostRuntimeDependenciesEnumeratorCompanion(),
  IAppxManifestHostRuntimeDependency:
      IAppxManifestHostRuntimeDependencyCompanion(),
  IAppxManifestHostRuntimeDependency2:
      IAppxManifestHostRuntimeDependency2Companion(),
  IAppxManifestMainPackageDependenciesEnumerator:
      IAppxManifestMainPackageDependenciesEnumeratorCompanion(),
  IAppxManifestMainPackageDependency:
      IAppxManifestMainPackageDependencyCompanion(),
  IAppxManifestOptionalPackageInfo: IAppxManifestOptionalPackageInfoCompanion(),
  IAppxManifestOSPackageDependenciesEnumerator:
      IAppxManifestOSPackageDependenciesEnumeratorCompanion(),
  IAppxManifestOSPackageDependency: IAppxManifestOSPackageDependencyCompanion(),
  IAppxManifestPackageDependenciesEnumerator:
      IAppxManifestPackageDependenciesEnumeratorCompanion(),
  IAppxManifestPackageDependency: IAppxManifestPackageDependencyCompanion(),
  IAppxManifestPackageId: IAppxManifestPackageIdCompanion(),
  IAppxManifestProperties: IAppxManifestPropertiesCompanion(),
  IAppxManifestQualifiedResource: IAppxManifestQualifiedResourceCompanion(),
  IAppxManifestQualifiedResourcesEnumerator:
      IAppxManifestQualifiedResourcesEnumeratorCompanion(),
  IAppxManifestReader: IAppxManifestReaderCompanion(),
  IAppxManifestReader2: IAppxManifestReader2Companion(),
  IAppxManifestReader3: IAppxManifestReader3Companion(),
  IAppxManifestReader4: IAppxManifestReader4Companion(),
  IAppxManifestReader5: IAppxManifestReader5Companion(),
  IAppxManifestReader6: IAppxManifestReader6Companion(),
  IAppxManifestReader7: IAppxManifestReader7Companion(),
  IAppxManifestResourcesEnumerator: IAppxManifestResourcesEnumeratorCompanion(),
  IAppxManifestTargetDeviceFamiliesEnumerator:
      IAppxManifestTargetDeviceFamiliesEnumeratorCompanion(),
  IAppxManifestTargetDeviceFamily: IAppxManifestTargetDeviceFamilyCompanion(),
  IAppxPackageReader: IAppxPackageReaderCompanion(),
  IAppxPackageWriter: IAppxPackageWriterCompanion(),
  IAudioCaptureClient: IAudioCaptureClientCompanion(),
  IAudioClient: IAudioClientCompanion(),
  IAudioClient2: IAudioClient2Companion(),
  IAudioClient3: IAudioClient3Companion(),
  IAudioClientDuckingControl: IAudioClientDuckingControlCompanion(),
  IAudioClock: IAudioClockCompanion(),
  IAudioClock2: IAudioClock2Companion(),
  IAudioClockAdjustment: IAudioClockAdjustmentCompanion(),
  IAudioRenderClient: IAudioRenderClientCompanion(),
  IAudioSessionControl: IAudioSessionControlCompanion(),
  IAudioSessionControl2: IAudioSessionControl2Companion(),
  IAudioSessionEnumerator: IAudioSessionEnumeratorCompanion(),
  IAudioSessionEvents: IAudioSessionEventsCompanion(),
  IAudioSessionManager: IAudioSessionManagerCompanion(),
  IAudioSessionManager2: IAudioSessionManager2Companion(),
  IAudioSessionNotification: IAudioSessionNotificationCompanion(),
  IAudioStreamVolume: IAudioStreamVolumeCompanion(),
  IAudioVolumeDuckNotification: IAudioVolumeDuckNotificationCompanion(),
  IBindCtx: IBindCtxCompanion(),
  IChannelAudioVolume: IChannelAudioVolumeCompanion(),
  IClassFactory: IClassFactoryCompanion(),
  IConnectionPoint: IConnectionPointCompanion(),
  IConnectionPointContainer: IConnectionPointContainerCompanion(),
  ID3D11Asynchronous: ID3D11AsynchronousCompanion(),
  ID3D11AuthenticatedChannel: ID3D11AuthenticatedChannelCompanion(),
  ID3D11BlendState: ID3D11BlendStateCompanion(),
  ID3D11BlendState1: ID3D11BlendState1Companion(),
  ID3D11Buffer: ID3D11BufferCompanion(),
  ID3D11ClassInstance: ID3D11ClassInstanceCompanion(),
  ID3D11ClassLinkage: ID3D11ClassLinkageCompanion(),
  ID3D11CommandList: ID3D11CommandListCompanion(),
  ID3D11ComputeShader: ID3D11ComputeShaderCompanion(),
  ID3D11Counter: ID3D11CounterCompanion(),
  ID3D11CryptoSession: ID3D11CryptoSessionCompanion(),
  ID3D11Debug: ID3D11DebugCompanion(),
  ID3D11DepthStencilState: ID3D11DepthStencilStateCompanion(),
  ID3D11DepthStencilView: ID3D11DepthStencilViewCompanion(),
  ID3D11Device: ID3D11DeviceCompanion(),
  ID3D11Device1: ID3D11Device1Companion(),
  ID3D11Device2: ID3D11Device2Companion(),
  ID3D11Device3: ID3D11Device3Companion(),
  ID3D11Device4: ID3D11Device4Companion(),
  ID3D11Device5: ID3D11Device5Companion(),
  ID3D11DeviceChild: ID3D11DeviceChildCompanion(),
  ID3D11DeviceContext: ID3D11DeviceContextCompanion(),
  ID3D11DeviceContext1: ID3D11DeviceContext1Companion(),
  ID3D11DeviceContext2: ID3D11DeviceContext2Companion(),
  ID3D11DeviceContext3: ID3D11DeviceContext3Companion(),
  ID3D11DeviceContext4: ID3D11DeviceContext4Companion(),
  ID3D11DomainShader: ID3D11DomainShaderCompanion(),
  ID3D11Fence: ID3D11FenceCompanion(),
  ID3D11FunctionLinkingGraph: ID3D11FunctionLinkingGraphCompanion(),
  ID3D11FunctionParameterReflection:
      ID3D11FunctionParameterReflectionCompanion(),
  ID3D11FunctionReflection: ID3D11FunctionReflectionCompanion(),
  ID3D11GeometryShader: ID3D11GeometryShaderCompanion(),
  ID3D11HullShader: ID3D11HullShaderCompanion(),
  ID3D11InfoQueue: ID3D11InfoQueueCompanion(),
  ID3D11InputLayout: ID3D11InputLayoutCompanion(),
  ID3D11LibraryReflection: ID3D11LibraryReflectionCompanion(),
  ID3D11Linker: ID3D11LinkerCompanion(),
  ID3D11LinkingNode: ID3D11LinkingNodeCompanion(),
  ID3D11Module: ID3D11ModuleCompanion(),
  ID3D11ModuleInstance: ID3D11ModuleInstanceCompanion(),
  ID3D11Multithread: ID3D11MultithreadCompanion(),
  ID3D11PixelShader: ID3D11PixelShaderCompanion(),
  ID3D11Predicate: ID3D11PredicateCompanion(),
  ID3D11Query: ID3D11QueryCompanion(),
  ID3D11Query1: ID3D11Query1Companion(),
  ID3D11RasterizerState: ID3D11RasterizerStateCompanion(),
  ID3D11RasterizerState1: ID3D11RasterizerState1Companion(),
  ID3D11RasterizerState2: ID3D11RasterizerState2Companion(),
  ID3D11RefDefaultTrackingOptions: ID3D11RefDefaultTrackingOptionsCompanion(),
  ID3D11RefTrackingOptions: ID3D11RefTrackingOptionsCompanion(),
  ID3D11RenderTargetView: ID3D11RenderTargetViewCompanion(),
  ID3D11RenderTargetView1: ID3D11RenderTargetView1Companion(),
  ID3D11Resource: ID3D11ResourceCompanion(),
  ID3D11SamplerState: ID3D11SamplerStateCompanion(),
  ID3D11ShaderReflection: ID3D11ShaderReflectionCompanion(),
  ID3D11ShaderReflectionConstantBuffer:
      ID3D11ShaderReflectionConstantBufferCompanion(),
  ID3D11ShaderReflectionType: ID3D11ShaderReflectionTypeCompanion(),
  ID3D11ShaderReflectionVariable: ID3D11ShaderReflectionVariableCompanion(),
  ID3D11ShaderResourceView: ID3D11ShaderResourceViewCompanion(),
  ID3D11ShaderResourceView1: ID3D11ShaderResourceView1Companion(),
  ID3D11ShaderTrace: ID3D11ShaderTraceCompanion(),
  ID3D11ShaderTraceFactory: ID3D11ShaderTraceFactoryCompanion(),
  ID3D11SwitchToRef: ID3D11SwitchToRefCompanion(),
  ID3D11Texture1D: ID3D11Texture1DCompanion(),
  ID3D11Texture2D: ID3D11Texture2DCompanion(),
  ID3D11Texture2D1: ID3D11Texture2D1Companion(),
  ID3D11Texture3D: ID3D11Texture3DCompanion(),
  ID3D11Texture3D1: ID3D11Texture3D1Companion(),
  ID3D11TracingDevice: ID3D11TracingDeviceCompanion(),
  ID3D11UnorderedAccessView: ID3D11UnorderedAccessViewCompanion(),
  ID3D11UnorderedAccessView1: ID3D11UnorderedAccessView1Companion(),
  ID3D11VertexShader: ID3D11VertexShaderCompanion(),
  ID3D11VideoContext: ID3D11VideoContextCompanion(),
  ID3D11VideoContext1: ID3D11VideoContext1Companion(),
  ID3D11VideoContext2: ID3D11VideoContext2Companion(),
  ID3D11VideoContext3: ID3D11VideoContext3Companion(),
  ID3D11VideoDecoder: ID3D11VideoDecoderCompanion(),
  ID3D11VideoDecoderOutputView: ID3D11VideoDecoderOutputViewCompanion(),
  ID3D11VideoDevice: ID3D11VideoDeviceCompanion(),
  ID3D11VideoDevice1: ID3D11VideoDevice1Companion(),
  ID3D11VideoDevice2: ID3D11VideoDevice2Companion(),
  ID3D11VideoProcessor: ID3D11VideoProcessorCompanion(),
  ID3D11VideoProcessorEnumerator: ID3D11VideoProcessorEnumeratorCompanion(),
  ID3D11VideoProcessorEnumerator1: ID3D11VideoProcessorEnumerator1Companion(),
  ID3D11VideoProcessorInputView: ID3D11VideoProcessorInputViewCompanion(),
  ID3D11VideoProcessorOutputView: ID3D11VideoProcessorOutputViewCompanion(),
  ID3D11View: ID3D11ViewCompanion(),
  ID3DBlob: ID3DBlobCompanion(),
  ID3DDeviceContextState: ID3DDeviceContextStateCompanion(),
  ID3DUserDefinedAnnotation: ID3DUserDefinedAnnotationCompanion(),
  ID3DX11FFT: ID3DX11FFTCompanion(),
  ID3DX11Scan: ID3DX11ScanCompanion(),
  ID3DX11SegmentedScan: ID3DX11SegmentedScanCompanion(),
  IDCompositionAffineTransform2DEffect:
      IDCompositionAffineTransform2DEffectCompanion(),
  IDCompositionAnimation: IDCompositionAnimationCompanion(),
  IDCompositionArithmeticCompositeEffect:
      IDCompositionArithmeticCompositeEffectCompanion(),
  IDCompositionBlendEffect: IDCompositionBlendEffectCompanion(),
  IDCompositionBrightnessEffect: IDCompositionBrightnessEffectCompanion(),
  IDCompositionClip: IDCompositionClipCompanion(),
  IDCompositionColorMatrixEffect: IDCompositionColorMatrixEffectCompanion(),
  IDCompositionCompositeEffect: IDCompositionCompositeEffectCompanion(),
  IDCompositionDelegatedInkTrail: IDCompositionDelegatedInkTrailCompanion(),
  IDCompositionDesktopDevice: IDCompositionDesktopDeviceCompanion(),
  IDCompositionDevice: IDCompositionDeviceCompanion(),
  IDCompositionDevice2: IDCompositionDevice2Companion(),
  IDCompositionDevice3: IDCompositionDevice3Companion(),
  IDCompositionDevice4: IDCompositionDevice4Companion(),
  IDCompositionDevice5: IDCompositionDevice5Companion(),
  IDCompositionDeviceDebug: IDCompositionDeviceDebugCompanion(),
  IDCompositionDynamicTexture: IDCompositionDynamicTextureCompanion(),
  IDCompositionEffect: IDCompositionEffectCompanion(),
  IDCompositionEffectGroup: IDCompositionEffectGroupCompanion(),
  IDCompositionFilterEffect: IDCompositionFilterEffectCompanion(),
  IDCompositionGaussianBlurEffect: IDCompositionGaussianBlurEffectCompanion(),
  IDCompositionHueRotationEffect: IDCompositionHueRotationEffectCompanion(),
  IDCompositionInkTrailDevice: IDCompositionInkTrailDeviceCompanion(),
  IDCompositionLinearTransferEffect:
      IDCompositionLinearTransferEffectCompanion(),
  IDCompositionMatrixTransform: IDCompositionMatrixTransformCompanion(),
  IDCompositionMatrixTransform3D: IDCompositionMatrixTransform3DCompanion(),
  IDCompositionRectangleClip: IDCompositionRectangleClipCompanion(),
  IDCompositionRotateTransform: IDCompositionRotateTransformCompanion(),
  IDCompositionRotateTransform3D: IDCompositionRotateTransform3DCompanion(),
  IDCompositionSaturationEffect: IDCompositionSaturationEffectCompanion(),
  IDCompositionScaleTransform: IDCompositionScaleTransformCompanion(),
  IDCompositionScaleTransform3D: IDCompositionScaleTransform3DCompanion(),
  IDCompositionShadowEffect: IDCompositionShadowEffectCompanion(),
  IDCompositionSkewTransform: IDCompositionSkewTransformCompanion(),
  IDCompositionSurface: IDCompositionSurfaceCompanion(),
  IDCompositionSurfaceFactory: IDCompositionSurfaceFactoryCompanion(),
  IDCompositionTableTransferEffect: IDCompositionTableTransferEffectCompanion(),
  IDCompositionTarget: IDCompositionTargetCompanion(),
  IDCompositionTexture: IDCompositionTextureCompanion(),
  IDCompositionTransform: IDCompositionTransformCompanion(),
  IDCompositionTransform3D: IDCompositionTransform3DCompanion(),
  IDCompositionTranslateTransform: IDCompositionTranslateTransformCompanion(),
  IDCompositionTranslateTransform3D:
      IDCompositionTranslateTransform3DCompanion(),
  IDCompositionTurbulenceEffect: IDCompositionTurbulenceEffectCompanion(),
  IDCompositionVirtualSurface: IDCompositionVirtualSurfaceCompanion(),
  IDCompositionVisual: IDCompositionVisualCompanion(),
  IDCompositionVisual2: IDCompositionVisual2Companion(),
  IDCompositionVisual3: IDCompositionVisual3Companion(),
  IDCompositionVisualDebug: IDCompositionVisualDebugCompanion(),
  IDesktopWallpaper: IDesktopWallpaperCompanion(),
  IDispatch: IDispatchCompanion(),
  IDXGIAdapter: IDXGIAdapterCompanion(),
  IDXGIDevice: IDXGIDeviceCompanion(),
  IDXGIDeviceSubObject: IDXGIDeviceSubObjectCompanion(),
  IDXGIObject: IDXGIObjectCompanion(),
  IDXGIOutput: IDXGIOutputCompanion(),
  IDXGISurface: IDXGISurfaceCompanion(),
  IDXGISurface1: IDXGISurface1Companion(),
  IDXGISwapChain: IDXGISwapChainCompanion(),
  IEnumConnectionPoints: IEnumConnectionPointsCompanion(),
  IEnumConnections: IEnumConnectionsCompanion(),
  IEnumIDList: IEnumIDListCompanion(),
  IEnumMoniker: IEnumMonikerCompanion(),
  IEnumNetworkConnections: IEnumNetworkConnectionsCompanion(),
  IEnumNetworks: IEnumNetworksCompanion(),
  IEnumResources: IEnumResourcesCompanion(),
  IEnumShellItems: IEnumShellItemsCompanion(),
  IEnumSpellingError: IEnumSpellingErrorCompanion(),
  IEnumSpObjectTokens: IEnumSpObjectTokensCompanion(),
  IEnumSTATSTG: IEnumSTATSTGCompanion(),
  IEnumString: IEnumStringCompanion(),
  IEnumVARIANT: IEnumVARIANTCompanion(),
  IEnumWbemClassObject: IEnumWbemClassObjectCompanion(),
  IErrorInfo: IErrorInfoCompanion(),
  IFileDialog: IFileDialogCompanion(),
  IFileDialog2: IFileDialog2Companion(),
  IFileDialogCustomize: IFileDialogCustomizeCompanion(),
  IFileDialogEvents: IFileDialogEventsCompanion(),
  IFileIsInUse: IFileIsInUseCompanion(),
  IFileOpenDialog: IFileOpenDialogCompanion(),
  IFileOperationProgressSink: IFileOperationProgressSinkCompanion(),
  IFileSaveDialog: IFileSaveDialogCompanion(),
  IInitializeWithWindow: IInitializeWithWindowCompanion(),
  IInspectable: IInspectableCompanion(),
  IKnownFolder: IKnownFolderCompanion(),
  IKnownFolderManager: IKnownFolderManagerCompanion(),
  IMalloc: IMallocCompanion(),
  IMetaDataAssemblyImport: IMetaDataAssemblyImportCompanion(),
  IMetaDataDispenser: IMetaDataDispenserCompanion(),
  IMetaDataDispenserEx: IMetaDataDispenserExCompanion(),
  IMetaDataImport: IMetaDataImportCompanion(),
  IMetaDataImport2: IMetaDataImport2Companion(),
  IMetaDataTables: IMetaDataTablesCompanion(),
  IMetaDataTables2: IMetaDataTables2Companion(),
  IMMDevice: IMMDeviceCompanion(),
  IMMDeviceCollection: IMMDeviceCollectionCompanion(),
  IMMDeviceEnumerator: IMMDeviceEnumeratorCompanion(),
  IMMEndpoint: IMMEndpointCompanion(),
  IMMNotificationClient: IMMNotificationClientCompanion(),
  IModalWindow: IModalWindowCompanion(),
  IMoniker: IMonikerCompanion(),
  INetwork: INetworkCompanion(),
  INetworkConnection: INetworkConnectionCompanion(),
  INetworkListManager: INetworkListManagerCompanion(),
  INetworkListManagerEvents: INetworkListManagerEventsCompanion(),
  IOptionDescription: IOptionDescriptionCompanion(),
  IPersist: IPersistCompanion(),
  IPersistFile: IPersistFileCompanion(),
  IPersistMemory: IPersistMemoryCompanion(),
  IPersistStream: IPersistStreamCompanion(),
  IPortableDeviceKeyCollection: IPortableDeviceKeyCollectionCompanion(),
  IPortableDevicePropVariantCollection:
      IPortableDevicePropVariantCollectionCompanion(),
  IPortableDeviceValues: IPortableDeviceValuesCompanion(),
  IPortableDeviceValuesCollection: IPortableDeviceValuesCollectionCompanion(),
  IPropertyDescriptionList: IPropertyDescriptionListCompanion(),
  IPropertyStore: IPropertyStoreCompanion(),
  IProvideClassInfo: IProvideClassInfoCompanion(),
  IRawElementProviderSimple: IRawElementProviderSimpleCompanion(),
  IRecordInfo: IRecordInfoCompanion(),
  IRestrictedErrorInfo: IRestrictedErrorInfoCompanion(),
  IRunningObjectTable: IRunningObjectTableCompanion(),
  ISensor: ISensorCompanion(),
  ISensorCollection: ISensorCollectionCompanion(),
  ISensorDataReport: ISensorDataReportCompanion(),
  ISensorEvents: ISensorEventsCompanion(),
  ISensorManager: ISensorManagerCompanion(),
  ISensorManagerEvents: ISensorManagerEventsCompanion(),
  ISequentialStream: ISequentialStreamCompanion(),
  IShellFolder: IShellFolderCompanion(),
  IShellItem: IShellItemCompanion(),
  IShellItem2: IShellItem2Companion(),
  IShellItemArray: IShellItemArrayCompanion(),
  IShellItemFilter: IShellItemFilterCompanion(),
  IShellItemImageFactory: IShellItemImageFactoryCompanion(),
  IShellItemResources: IShellItemResourcesCompanion(),
  IShellLink: IShellLinkCompanion(),
  IShellLinkDataList: IShellLinkDataListCompanion(),
  IShellLinkDual: IShellLinkDualCompanion(),
  IShellService: IShellServiceCompanion(),
  ISimpleAudioVolume: ISimpleAudioVolumeCompanion(),
  ISpDataKey: ISpDataKeyCompanion(),
  ISpeechAudioFormat: ISpeechAudioFormatCompanion(),
  ISpeechBaseStream: ISpeechBaseStreamCompanion(),
  ISpeechDataKey: ISpeechDataKeyCompanion(),
  ISpeechObjectToken: ISpeechObjectTokenCompanion(),
  ISpeechObjectTokenCategory: ISpeechObjectTokenCategoryCompanion(),
  ISpeechObjectTokens: ISpeechObjectTokensCompanion(),
  ISpeechVoice: ISpeechVoiceCompanion(),
  ISpeechVoiceStatus: ISpeechVoiceStatusCompanion(),
  ISpeechWaveFormatEx: ISpeechWaveFormatExCompanion(),
  ISpellChecker: ISpellCheckerCompanion(),
  ISpellChecker2: ISpellChecker2Companion(),
  ISpellCheckerChangedEventHandler: ISpellCheckerChangedEventHandlerCompanion(),
  ISpellCheckerFactory: ISpellCheckerFactoryCompanion(),
  ISpellingError: ISpellingErrorCompanion(),
  ISpEventSource: ISpEventSourceCompanion(),
  ISpNotifySink: ISpNotifySinkCompanion(),
  ISpNotifySource: ISpNotifySourceCompanion(),
  ISpObjectToken: ISpObjectTokenCompanion(),
  ISpObjectTokenCategory: ISpObjectTokenCategoryCompanion(),
  ISpStreamFormat: ISpStreamFormatCompanion(),
  ISpVoice: ISpVoiceCompanion(),
  IStorage: IStorageCompanion(),
  IStream: IStreamCompanion(),
  ISupportErrorInfo: ISupportErrorInfoCompanion(),
  ITypeComp: ITypeCompCompanion(),
  ITypeInfo: ITypeInfoCompanion(),
  ITypeLib: ITypeLibCompanion(),
  IUIAutomation: IUIAutomationCompanion(),
  IUIAutomation2: IUIAutomation2Companion(),
  IUIAutomation3: IUIAutomation3Companion(),
  IUIAutomation4: IUIAutomation4Companion(),
  IUIAutomation5: IUIAutomation5Companion(),
  IUIAutomation6: IUIAutomation6Companion(),
  IUIAutomationActiveTextPositionChangedEventHandler:
      IUIAutomationActiveTextPositionChangedEventHandlerCompanion(),
  IUIAutomationAndCondition: IUIAutomationAndConditionCompanion(),
  IUIAutomationAnnotationPattern: IUIAutomationAnnotationPatternCompanion(),
  IUIAutomationBoolCondition: IUIAutomationBoolConditionCompanion(),
  IUIAutomationCacheRequest: IUIAutomationCacheRequestCompanion(),
  IUIAutomationChangesEventHandler: IUIAutomationChangesEventHandlerCompanion(),
  IUIAutomationCondition: IUIAutomationConditionCompanion(),
  IUIAutomationCustomNavigationPattern:
      IUIAutomationCustomNavigationPatternCompanion(),
  IUIAutomationDockPattern: IUIAutomationDockPatternCompanion(),
  IUIAutomationDragPattern: IUIAutomationDragPatternCompanion(),
  IUIAutomationDropTargetPattern: IUIAutomationDropTargetPatternCompanion(),
  IUIAutomationElement: IUIAutomationElementCompanion(),
  IUIAutomationElement2: IUIAutomationElement2Companion(),
  IUIAutomationElement3: IUIAutomationElement3Companion(),
  IUIAutomationElement4: IUIAutomationElement4Companion(),
  IUIAutomationElement5: IUIAutomationElement5Companion(),
  IUIAutomationElement6: IUIAutomationElement6Companion(),
  IUIAutomationElement7: IUIAutomationElement7Companion(),
  IUIAutomationElement8: IUIAutomationElement8Companion(),
  IUIAutomationElement9: IUIAutomationElement9Companion(),
  IUIAutomationElementArray: IUIAutomationElementArrayCompanion(),
  IUIAutomationEventHandler: IUIAutomationEventHandlerCompanion(),
  IUIAutomationEventHandlerGroup: IUIAutomationEventHandlerGroupCompanion(),
  IUIAutomationExpandCollapsePattern:
      IUIAutomationExpandCollapsePatternCompanion(),
  IUIAutomationFocusChangedEventHandler:
      IUIAutomationFocusChangedEventHandlerCompanion(),
  IUIAutomationGridItemPattern: IUIAutomationGridItemPatternCompanion(),
  IUIAutomationGridPattern: IUIAutomationGridPatternCompanion(),
  IUIAutomationInvokePattern: IUIAutomationInvokePatternCompanion(),
  IUIAutomationItemContainerPattern:
      IUIAutomationItemContainerPatternCompanion(),
  IUIAutomationLegacyIAccessiblePattern:
      IUIAutomationLegacyIAccessiblePatternCompanion(),
  IUIAutomationMultipleViewPattern: IUIAutomationMultipleViewPatternCompanion(),
  IUIAutomationNotCondition: IUIAutomationNotConditionCompanion(),
  IUIAutomationNotificationEventHandler:
      IUIAutomationNotificationEventHandlerCompanion(),
  IUIAutomationObjectModelPattern: IUIAutomationObjectModelPatternCompanion(),
  IUIAutomationOrCondition: IUIAutomationOrConditionCompanion(),
  IUIAutomationPropertyChangedEventHandler:
      IUIAutomationPropertyChangedEventHandlerCompanion(),
  IUIAutomationPropertyCondition: IUIAutomationPropertyConditionCompanion(),
  IUIAutomationProxyFactory: IUIAutomationProxyFactoryCompanion(),
  IUIAutomationProxyFactoryEntry: IUIAutomationProxyFactoryEntryCompanion(),
  IUIAutomationProxyFactoryMapping: IUIAutomationProxyFactoryMappingCompanion(),
  IUIAutomationRangeValuePattern: IUIAutomationRangeValuePatternCompanion(),
  IUIAutomationScrollItemPattern: IUIAutomationScrollItemPatternCompanion(),
  IUIAutomationScrollPattern: IUIAutomationScrollPatternCompanion(),
  IUIAutomationSelectionItemPattern:
      IUIAutomationSelectionItemPatternCompanion(),
  IUIAutomationSelectionPattern: IUIAutomationSelectionPatternCompanion(),
  IUIAutomationSelectionPattern2: IUIAutomationSelectionPattern2Companion(),
  IUIAutomationSpreadsheetItemPattern:
      IUIAutomationSpreadsheetItemPatternCompanion(),
  IUIAutomationSpreadsheetPattern: IUIAutomationSpreadsheetPatternCompanion(),
  IUIAutomationStructureChangedEventHandler:
      IUIAutomationStructureChangedEventHandlerCompanion(),
  IUIAutomationStylesPattern: IUIAutomationStylesPatternCompanion(),
  IUIAutomationSynchronizedInputPattern:
      IUIAutomationSynchronizedInputPatternCompanion(),
  IUIAutomationTableItemPattern: IUIAutomationTableItemPatternCompanion(),
  IUIAutomationTablePattern: IUIAutomationTablePatternCompanion(),
  IUIAutomationTextChildPattern: IUIAutomationTextChildPatternCompanion(),
  IUIAutomationTextEditPattern: IUIAutomationTextEditPatternCompanion(),
  IUIAutomationTextEditTextChangedEventHandler:
      IUIAutomationTextEditTextChangedEventHandlerCompanion(),
  IUIAutomationTextPattern: IUIAutomationTextPatternCompanion(),
  IUIAutomationTextPattern2: IUIAutomationTextPattern2Companion(),
  IUIAutomationTextRange: IUIAutomationTextRangeCompanion(),
  IUIAutomationTextRange2: IUIAutomationTextRange2Companion(),
  IUIAutomationTextRange3: IUIAutomationTextRange3Companion(),
  IUIAutomationTextRangeArray: IUIAutomationTextRangeArrayCompanion(),
  IUIAutomationTogglePattern: IUIAutomationTogglePatternCompanion(),
  IUIAutomationTransformPattern: IUIAutomationTransformPatternCompanion(),
  IUIAutomationTransformPattern2: IUIAutomationTransformPattern2Companion(),
  IUIAutomationTreeWalker: IUIAutomationTreeWalkerCompanion(),
  IUIAutomationValuePattern: IUIAutomationValuePatternCompanion(),
  IUIAutomationVirtualizedItemPattern:
      IUIAutomationVirtualizedItemPatternCompanion(),
  IUIAutomationWindowPattern: IUIAutomationWindowPatternCompanion(),
  IUnknown: IUnknownCompanion(),
  IUri: IUriCompanion(),
  IVirtualDesktopManager: IVirtualDesktopManagerCompanion(),
  IWbemCallResult: IWbemCallResultCompanion(),
  IWbemClassObject: IWbemClassObjectCompanion(),
  IWbemConfigureRefresher: IWbemConfigureRefresherCompanion(),
  IWbemContext: IWbemContextCompanion(),
  IWbemHiPerfEnum: IWbemHiPerfEnumCompanion(),
  IWbemLocator: IWbemLocatorCompanion(),
  IWbemObjectAccess: IWbemObjectAccessCompanion(),
  IWbemObjectSink: IWbemObjectSinkCompanion(),
  IWbemQualifierSet: IWbemQualifierSetCompanion(),
  IWbemRefresher: IWbemRefresherCompanion(),
  IWbemServices: IWbemServicesCompanion(),
  IWebAuthenticationCoreManagerInterop:
      IWebAuthenticationCoreManagerInteropCompanion(),
  IWinHttpRequest: IWinHttpRequestCompanion(),
};
