// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const D3D_COMPILER_VERSION = 0x2f;
const D3DCOMPILE_DEBUG = 0x1;
const D3DCOMPILE_SKIP_VALIDATION = 0x2;
const D3DCOMPILE_SKIP_OPTIMIZATION = 0x4;
const D3DCOMPILE_PACK_MATRIX_ROW_MAJOR = 0x8;
const D3DCOMPILE_PACK_MATRIX_COLUMN_MAJOR = 0x10;
const D3DCOMPILE_PARTIAL_PRECISION = 0x20;
const D3DCOMPILE_FORCE_VS_SOFTWARE_NO_OPT = 0x40;
const D3DCOMPILE_FORCE_PS_SOFTWARE_NO_OPT = 0x80;
const D3DCOMPILE_NO_PRESHADER = 0x100;
const D3DCOMPILE_AVOID_FLOW_CONTROL = 0x200;
const D3DCOMPILE_PREFER_FLOW_CONTROL = 0x400;
const D3DCOMPILE_ENABLE_STRICTNESS = 0x800;
const D3DCOMPILE_ENABLE_BACKWARDS_COMPATIBILITY = 0x1000;
const D3DCOMPILE_IEEE_STRICTNESS = 0x2000;
const D3DCOMPILE_OPTIMIZATION_LEVEL0 = 0x4000;
const D3DCOMPILE_OPTIMIZATION_LEVEL1 = 0x0;
const D3DCOMPILE_OPTIMIZATION_LEVEL3 = 0x8000;
const D3DCOMPILE_RESERVED16 = 0x10000;
const D3DCOMPILE_RESERVED17 = 0x20000;
const D3DCOMPILE_WARNINGS_ARE_ERRORS = 0x40000;
const D3DCOMPILE_RESOURCES_MAY_ALIAS = 0x80000;
const D3DCOMPILE_ENABLE_UNBOUNDED_DESCRIPTOR_TABLES = 0x100000;
const D3DCOMPILE_ALL_RESOURCES_BOUND = 0x200000;
const D3DCOMPILE_DEBUG_NAME_FOR_SOURCE = 0x400000;
const D3DCOMPILE_DEBUG_NAME_FOR_BINARY = 0x800000;
const D3DCOMPILE_EFFECT_CHILD_EFFECT = 0x1;
const D3DCOMPILE_EFFECT_ALLOW_SLOW_OPS = 0x2;
const D3DCOMPILE_FLAGS2_FORCE_ROOT_SIGNATURE_LATEST = 0x0;
const D3DCOMPILE_FLAGS2_FORCE_ROOT_SIGNATURE_1_0 = 0x10;
const D3DCOMPILE_FLAGS2_FORCE_ROOT_SIGNATURE_1_1 = 0x20;
const D3DCOMPILE_SECDATA_MERGE_UAV_SLOTS = 0x1;
const D3DCOMPILE_SECDATA_PRESERVE_TEMPLATE_SLOTS = 0x2;
const D3DCOMPILE_SECDATA_REQUIRE_TEMPLATE_MATCH = 0x4;
const D3D_DISASM_ENABLE_COLOR_CODE = 0x1;
const D3D_DISASM_ENABLE_DEFAULT_VALUE_PRINTS = 0x2;
const D3D_DISASM_ENABLE_INSTRUCTION_NUMBERING = 0x4;
const D3D_DISASM_ENABLE_INSTRUCTION_CYCLE = 0x8;
const D3D_DISASM_DISABLE_DEBUG_INFO = 0x10;
const D3D_DISASM_ENABLE_INSTRUCTION_OFFSET = 0x20;
const D3D_DISASM_INSTRUCTION_ONLY = 0x40;
const D3D_DISASM_PRINT_HEX_LITERALS = 0x80;
const D3D_GET_INST_OFFSETS_INCLUDE_NON_EXECUTABLE = 0x1;
const D3D_COMPRESS_SHADER_KEEP_ALL_PARTS = 0x1;
