import 'dart:io';

import 'package:win32/src/hook_helpers/download.dart';
import 'package:win32/src/hook_helpers/targets.dart';

Future<void> main(List<String> args) async {
  final assetsDir = Directory.fromUri(
    Platform.script.resolve('../.dart_tool/win32/'),
  );
  if (assetsDir.existsSync()) await assetsDir.delete(recursive: true);
  await assetsDir.create(recursive: true);
  await Future.wait([
    for (final (targetOS, targetArchitecture) in supportedTargets)
      downloadAsset(targetOS, targetArchitecture, assetsDir),
  ]);
  final assetFiles =
      assetsDir.listSync(recursive: true).whereType<File>().toList()
        ..sort((f1, f2) => f1.path.compareTo(f2.path));
  final assetHashes = <String, String>{};
  for (final assetFile in assetFiles) {
    final fileHash = await hashAsset(assetFile);
    final target = assetFile.uri.pathSegments.lastWhere((e) => e.isNotEmpty);
    assetHashes[target] = fileHash;
  }

  await writeHashesFile(assetHashes);
}

/// Writes the [assetHashes] map to `lib/src/hook_helpers/hashes.g.dart`.
Future<void> writeHashesFile(Map<String, String> assetHashes) async {
  final hashesFile = File.fromUri(
    Platform.script.resolve('../lib/src/hook_helpers/hashes.g.dart'),
  );
  await hashesFile.create(recursive: true);
  final buffer = StringBuffer()
    ..writeln('''
// THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
//
// TO UPDATE, RUN:
//
// dart run tool/generate_asset_hashes.dart
//
''')
    ..writeln()
    ..writeln('''
/// A map from asset file names to their MD5 hashes.
///
/// Used to verify the integrity of downloaded assets.
const assetHashes = <String, String>{
''');
  for (final hash in assetHashes.entries) {
    buffer.write("  '${hash.key}': '${hash.value}',\n");
  }
  buffer.writeln('};');
  await hashesFile.writeAsString(buffer.toString());
  await Process.run(Platform.executable, ['format', hashesFile.path]);
}
