import 'package:win32/winsock2.dart';

const $0 = ADDRESS_FAMILY.AF_INET;
const $1 = ADDRESS_FAMILY.AF_INET6;
const $2 = ADDRESS_FAMILY.AF_UNSPEC;
const $3 = WINSOCK_SOCKET_TYPE.SOCK_DGRAM;
const $4 = WINSOCK_SOCKET_TYPE.SOCK_RAW;
const $5 = WINSOCK_SOCKET_TYPE.SOCK_RDM;
const $6 = WINSOCK_SOCKET_TYPE.SOCK_SEQPACKET;
const $7 = WINSOCK_SOCKET_TYPE.SOCK_STREAM;
