// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const DXGI_USAGE_SHADER_INPUT = 0x10;
const DXGI_USAGE_RENDER_TARGET_OUTPUT = 0x20;
const DXGI_USAGE_BACK_BUFFER = 0x40;
const DXGI_USAGE_SHARED = 0x80;
const DXGI_USAGE_READ_ONLY = 0x100;
const DXGI_USAGE_DISCARD_ON_PRESENT = 0x200;
const DXGI_USAGE_UNORDERED_ACCESS = 0x400;
const DXGI_MAP_READ = 0x1;
const DXGI_MAP_WRITE = 0x2;
const DXGI_MAP_DISCARD = 0x4;
const DXGI_ENUM_MODES_INTERLACED = 0x1;
const DXGI_ENUM_MODES_SCALING = 0x2;
const DXGI_MAX_SWAP_CHAIN_BUFFERS = 0x10;
const DXGI_PRESENT_TEST = 0x1;
const DXGI_PRESENT_DO_NOT_SEQUENCE = 0x2;
const DXGI_PRESENT_RESTART = 0x4;
const DXGI_PRESENT_DO_NOT_WAIT = 0x8;
const DXGI_PRESENT_STEREO_PREFER_RIGHT = 0x10;
const DXGI_PRESENT_STEREO_TEMPORARY_MONO = 0x20;
const DXGI_PRESENT_RESTRICT_TO_OUTPUT = 0x40;
const DXGI_PRESENT_USE_DURATION = 0x100;
const DXGI_PRESENT_ALLOW_TEARING = 0x200;
const DXGI_MWA_NO_WINDOW_CHANGES = 0x1;
const DXGI_MWA_NO_ALT_ENTER = 0x2;
const DXGI_MWA_NO_PRINT_SCREEN = 0x4;
const DXGI_MWA_VALID = 0x7;
const DXGI_ENUM_MODES_STEREO = 0x4;
const DXGI_ENUM_MODES_DISABLED_STEREO = 0x8;
const DXGI_SHARED_RESOURCE_READ = 0x80000000;
const DXGI_SHARED_RESOURCE_WRITE = 0x1;
const DXGI_DEBUG_BINARY_VERSION = 0x1;
const DXGI_DEBUG_ALL = 0x0;
const DXGI_DEBUG_DX = 0x0;
const DXGI_DEBUG_DXGI = 0x0;
const DXGI_DEBUG_APP = 0x0;
const DXGI_INFO_QUEUE_MESSAGE_ID_STRING_FROM_APPLICATION = 0x0;
const DXGI_INFO_QUEUE_DEFAULT_MESSAGE_COUNT_LIMIT = 0x400;
const DXGI_CREATE_FACTORY_DEBUG = 0x1;
const DXGI_ERROR_INVALID_CALL = 0x887a0001;
const DXGI_ERROR_NOT_FOUND = 0x887a0002;
const DXGI_ERROR_MORE_DATA = 0x887a0003;
const DXGI_ERROR_UNSUPPORTED = 0x887a0004;
const DXGI_ERROR_DEVICE_REMOVED = 0x887a0005;
const DXGI_ERROR_DEVICE_HUNG = 0x887a0006;
const DXGI_ERROR_DEVICE_RESET = 0x887a0007;
const DXGI_ERROR_WAS_STILL_DRAWING = 0x887a000a;
const DXGI_ERROR_FRAME_STATISTICS_DISJOINT = 0x887a000b;
const DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE = 0x887a000c;
const DXGI_ERROR_DRIVER_INTERNAL_ERROR = 0x887a0020;
const DXGI_ERROR_NONEXCLUSIVE = 0x887a0021;
const DXGI_ERROR_NOT_CURRENTLY_AVAILABLE = 0x887a0022;
const DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED = 0x887a0023;
const DXGI_ERROR_REMOTE_OUTOFMEMORY = 0x887a0024;
const DXGI_ERROR_ACCESS_LOST = 0x887a0026;
const DXGI_ERROR_WAIT_TIMEOUT = 0x887a0027;
const DXGI_ERROR_SESSION_DISCONNECTED = 0x887a0028;
const DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE = 0x887a0029;
const DXGI_ERROR_CANNOT_PROTECT_CONTENT = 0x887a002a;
const DXGI_ERROR_ACCESS_DENIED = 0x887a002b;
const DXGI_ERROR_NAME_ALREADY_EXISTS = 0x887a002c;
const DXGI_ERROR_SDK_COMPONENT_MISSING = 0x887a002d;
const DXGI_ERROR_NOT_CURRENT = 0x887a002e;
const DXGI_ERROR_HW_PROTECTION_OUTOFMEMORY = 0x887a0030;
const DXGI_ERROR_DYNAMIC_CODE_POLICY_VIOLATION = 0x887a0031;
const DXGI_ERROR_NON_COMPOSITED_UI = 0x887a0032;
const DXGI_ERROR_MODE_CHANGE_IN_PROGRESS = 0x887a0025;
const DXGI_ERROR_CACHE_CORRUPT = 0x887a0033;
const DXGI_ERROR_CACHE_FULL = 0x887a0034;
const DXGI_ERROR_CACHE_HASH_COLLISION = 0x887a0035;
const DXGI_ERROR_ALREADY_EXISTS = 0x887a0036;
