// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const GNSS_DRIVER_VERSION_1 = 0x1;
const GNSS_DRIVER_VERSION_2 = 0x2;
const GNSS_DRIVER_VERSION_3 = 0x3;
const GNSS_DRIVER_VERSION_4 = 0x4;
const GNSS_DRIVER_VERSION_5 = 0x5;
const GNSS_DRIVER_VERSION_6 = 0x6;
const IOCTL_GNSS_SEND_PLATFORM_CAPABILITY = 0x220004;
const IOCTL_GNSS_GET_DEVICE_CAPABILITY = 0x220008;
const IOCTL_GNSS_SEND_DRIVERCOMMAND = 0x22000c;
const IOCTL_GNSS_START_FIXSESSION = 0x220040;
const IOCTL_GNSS_MODIFY_FIXSESSION = 0x220044;
const IOCTL_GNSS_STOP_FIXSESSION = 0x220048;
const IOCTL_GNSS_GET_FIXDATA = 0x22004c;
const IOCTL_GNSS_INJECT_AGNSS = 0x220080;
const IOCTL_GNSS_LISTEN_AGNSS = 0x2200c0;
const IOCTL_GNSS_LISTEN_ERROR = 0x2200c4;
const IOCTL_GNSS_LISTEN_NI = 0x220100;
const IOCTL_GNSS_SET_SUPL_HSLP = 0x220104;
const IOCTL_GNSS_CONFIG_SUPL_CERT = 0x220108;
const IOCTL_GNSS_RESPOND_NI = 0x22010c;
const IOCTL_GNSS_EXECUTE_CWTEST = 0x220110;
const IOCTL_GNSS_EXECUTE_SELFTEST = 0x220114;
const IOCTL_GNSS_GET_CHIPSETINFO = 0x220118;
const IOCTL_GNSS_LISTEN_NMEA = 0x22011c;
const IOCTL_GNSS_SET_V2UPL_CONFIG = 0x220120;
const IOCTL_GNSS_CREATE_GEOFENCE = 0x220140;
const IOCTL_GNSS_DELETE_GEOFENCE = 0x220144;
const IOCTL_GNSS_LISTEN_GEOFENCE_ALERT = 0x220148;
const IOCTL_GNSS_LISTEN_GEOFENCES_TRACKINGSTATUS = 0x22014c;
const IOCTL_GNSS_LISTEN_DRIVER_REQUEST = 0x220180;
const IOCTL_GNSS_START_BREADCRUMBING = 0x2201c0;
const IOCTL_GNSS_STOP_BREADCRUMBING = 0x2201c4;
const IOCTL_GNSS_LISTEN_BREADCRUMBING_ALERT = 0x2201c8;
const IOCTL_GNSS_POP_BREADCRUMBS = 0x2201cc;
const GNSS_AGNSSFORMAT_XTRA1 = 0x1;
const GNSS_AGNSSFORMAT_XTRA2 = 0x2;
const GNSS_AGNSSFORMAT_LTO = 0x4;
const GNSS_AGNSSFORMAT_XTRA3 = 0x8;
const GNSS_AGNSSFORMAT_XTRA3_1 = 0x10;
const GNSS_AGNSSFORMAT_XTRA3_2 = 0x20;
const GNSS_AGNSSFORMAT_XTRA_INT = 0x40;
const MAX_SERVER_URL_NAME = 0x104;
const MIN_GEOFENCES_REQUIRED = 0x64;
const BREADCRUMBING_UNSUPPORTED = 0x0;
const BREADCRUMBING_VERSION_1 = 0x1;
const MIN_BREADCRUMBS_SUPPORTED = 0x78;
const GNSS_SATELLITE_ANY = 0x0;
const GNSS_SATELLITE_GPS = 0x1;
const GNSS_SATELLITE_GLONASS = 0x2;
const GNSS_SATELLITE_BEIDOU = 0x4;
const GNSS_SATELLITE_GALILEO = 0x8;
const GNSS_OPERMODE_ANY = 0x0;
const GNSS_OPERMODE_MSA = 0x1;
const GNSS_OPERMODE_MSB = 0x2;
const GNSS_OPERMODE_MSS = 0x4;
const GNSS_OPERMODE_CELLID = 0x8;
const GNSS_OPERMODE_AFLT = 0x10;
const GNSS_OPERMODE_OTDOA = 0x20;
const GNSS_NMEALOGGING_NONE = 0x0;
const GNSS_NMEALOGGING_ALL = 0xff;
const GNSS_FIXDETAIL_BASIC = 0x1;
const GNSS_FIXDETAIL_ACCURACY = 0x2;
const GNSS_FIXDETAIL_SATELLITE = 0x4;
const GNSS_MAXSATELLITE = 0x40;
const GNSS_GEOFENCESUPPORT_SUPPORTED = 0x1;
const GNSS_GEOFENCESUPPORT_CIRCLE = 0x2;
const LOCATION_API_VERSION = 0x1;
const GUID_DEVINTERFACE_GNSS = 0x0;
