// vtable_start 6
[uuid(4BD682DD-7554-40E9-9A9B-82654EDE7E62)]
interface IPropertyValue : IInspectable
{
    [propget] HRESULT Type([out] [retval] Windows.Foundation.PropertyType* value);
    [propget] HRESULT IsNumericScalar([out] [retval] boolean* value);
    HRESULT GetUInt8([out] [retval] BYTE* value);
    HRESULT GetInt16([out] [retval] INT16* value);
    HRESULT GetUInt16([out] [retval] UINT16* value);
    HRESULT GetInt32([out] [retval] INT32* value);
    HRESULT GetUInt32([out] [retval] UINT32* value);
    HRESULT GetInt64([out] [retval] INT64* value);
    HRESULT GetUInt64([out] [retval] UINT64* value);
    HRESULT GetSingle([out] [retval] FLOAT* value);
    HRESULT GetDouble([out] [retval] DOUBLE* value);
    HRESULT GetChar16([out] [retval] WCHAR* value);
    HRESULT GetBoolean([out] [retval] boolean* value);
    HRESULT GetString([out] [retval] HSTRING* value);
    HRESULT GetGuid([out] [retval] GUID* value);
    HRESULT GetDateTime([out] [retval] Windows.Foundation.DateTime* value);
    HRESULT GetTimeSpan([out] [retval] Windows.Foundation.TimeSpan* value);
    HRESULT GetPoint([out] [retval] Windows.Foundation.Point* value);
    HRESULT GetSize([out] [retval] Windows.Foundation.Size* value);
    HRESULT GetRect([out] [retval] Windows.Foundation.Rect* value);
    HRESULT GetUInt8Array([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] BYTE** value);
    HRESULT GetInt16Array([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] INT16** value);
    HRESULT GetUInt16Array([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] UINT16** value);
    HRESULT GetInt32Array([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] INT32** value);
    HRESULT GetUInt32Array([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] UINT32** value);
    HRESULT GetInt64Array([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] INT64** value);
    HRESULT GetUInt64Array([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] UINT64** value);
    HRESULT GetSingleArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] FLOAT** value);
    HRESULT GetDoubleArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] DOUBLE** value);
    HRESULT GetChar16Array([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] WCHAR** value);
    HRESULT GetBooleanArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] boolean** value);
    HRESULT GetStringArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] HSTRING** value);
    HRESULT GetInspectableArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] IInspectable*** value);
    HRESULT GetGuidArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] GUID** value);
    HRESULT GetDateTimeArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] Windows.Foundation.DateTime** value);
    HRESULT GetTimeSpanArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] Windows.Foundation.TimeSpan** value);
    HRESULT GetPointArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] Windows.Foundation.Point** value);
    HRESULT GetSizeArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] Windows.Foundation.Size** value);
    HRESULT GetRectArray([out] UINT32* __valueSize, [out] [size_is(, *__valueSize)] Windows.Foundation.Rect** value);
}