// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

/// Set of Unicode suffixed (`W`) functions without corresponding ANSI variants.
///
/// This set serves as a reference to identify functions that have Unicode
/// suffixes (`W`) but lack corresponding ANSI variants. These functions
/// typically do not possess the `UnicodeAttribute` and used to determine
/// whether a given function name should have its Unicode suffix stripped.
const unicodeSuffixedFunctions = <String>{
  'BackupPerfRegistryToFileW',
  'CM_Get_Class_PropertyW',
  'CM_Get_Class_Property_ExW',
  'CM_Get_DevNode_PropertyW',
  'CM_Get_DevNode_Property_ExW',
  'CM_Get_Device_Interface_PropertyW',
  'CM_Get_Device_Interface_Property_ExW',
  'CM_Get_Device_Interface_Property_KeysW',
  'CM_Get_Device_Interface_Property_Keys_ExW',
  'CM_Set_Class_PropertyW',
  'CM_Set_Class_Property_ExW',
  'CM_Set_DevNode_PropertyW',
  'CM_Set_DevNode_Property_ExW',
  'CM_Set_Device_Interface_PropertyW',
  'CM_Set_Device_Interface_Property_ExW',
  'CertSrvBackupGetBackupLogsW',
  'CertSrvBackupGetDatabaseNamesW',
  'CertSrvBackupGetDynamicFileListW',
  'CertSrvBackupOpenFileW',
  'CertSrvBackupPrepareW',
  'CertSrvIsServerOnlineW',
  'CertSrvRestoreGetDatabaseLocationsW',
  'CertSrvRestorePrepareW',
  'CertSrvRestoreRegisterW',
  'CertSrvServerControlW',
  'CommandLineToArgvW',
  'CopyFileFromAppW',
  'CreateDirectoryFromAppW',
  'CreateFile2FromAppW',
  'CreateFileFromAppW',
  'CreateProcessWithLogonW',
  'CreateProcessWithTokenW',
  'CreateUrlCacheEntryExW',
  'CredUIReadSSOCredW',
  'CredUIStoreSSOCredW',
  'DeleteFileFromAppW',
  'DnsHostnameToComputerNameExW',
  'DsCrackSpn3W',
  'DsCrackSpn4W',
  'DsGetDcCloseW',
  'DsGetForestTrustInformationW',
  'DsGetRdnW',
  'DsMergeForestTrustInformationW',
  'DsReplicaGetInfo2W',
  'DsReplicaGetInfoW',
  'FaxRegisterRoutingExtensionW',
  'FaxRegisterServiceProviderW',
  'FaxUnregisterServiceProviderW',
  'FindFirstFileExFromAppW',
  'FindFirstFileNameTransactedW',
  'FindFirstFileNameW',
  'FindFirstStreamTransactedW',
  'FindFirstStreamW',
  'FindNextFileNameW',
  'FindNextStreamW',
  'FreeAddrInfoW',
  'GetAddrInfoW',
  'GetFileAttributesExFromAppW',
  'GetHostNameW',
  'GetNameInfoW',
  'GetRegistryValueWithFallbackW',
  'GetVolumeInformationByHandleW',
  'I_RpcBindingToStaticStringBindingW',
  'InetNtopW',
  'InetPtonW',
  'JetGetErrorInfoW',
  'MoveFileFromAppW',
  'PrivacyGetZonePreferenceW',
  'PrivacySetZonePreferenceW',
  'QueryActCtxSettingsW',
  'QueryActCtxW',
  'ReadDirectoryChangesExW',
  'ReadDirectoryChangesW',
  'RemoveDirectoryFromAppW',
  'ReplaceFileFromAppW',
  'RestorePerfRegistryFromFileW',
  'RunDll32ShimW',
  'SHCreateProcessAsUserW',
  'SHRegGetIntW',
  'SetComputerNameEx2W',
  'SetContextAttributesW',
  'SetFileAttributesFromAppW',
  'SetupDiGetClassPropertyExW',
  'SetupDiGetClassPropertyKeysExW',
  'SetupDiGetClassPropertyW',
  'SetupDiGetDeviceInterfacePropertyW',
  'SetupDiGetDevicePropertyW',
  'SetupDiSetClassPropertyExW',
  'SetupDiSetClassPropertyW',
  'SetupDiSetDeviceInterfacePropertyW',
  'SetupDiSetDevicePropertyW',
  'StiCreateInstanceW',
  'StrCatChainW',
  'StrCatW',
  'StrCmpLogicalW',
  'StrCmpW',
  'StrCpyW',
  'Str_SetPtrW',
  'UrlFixupW',
  'XcvDataW',
  'uaw_lstrcmpW',
  'uaw_lstrcmpiW',
  'uaw_lstrlenW',
};

/// Set of Unicode suffixed (`W`) typeDefs without corresponding ANSI variants.
///
/// This set serves as a reference to identify typeDefs that have Unicode
/// suffixes (`W`) but lack corresponding ANSI variants. These typically do not
/// possess the `UnicodeAttribute` and used to determine whether a given typeDef
/// name should have its Unicode suffix stripped.
const unicodeSuffixedTypeDefs = <String>{
  'AsyncIMSAdminBaseSinkW',
  'DS_REPL_CURSORS_3W',
  'DS_REPL_CURSOR_3W',
  'IMSAdminBase2W',
  'IMSAdminBase3W',
  'IMSAdminBaseSinkW',
  'IMSAdminBaseW',
  'IMSImpExpHelpW',
  'IStillImageW',
  'SecPkgCredentials_KdcProxySettingsW',
};
