// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const ASN_UNIVERSAL = 0x0;
const ASN_APPLICATION = 0x40;
const ASN_CONTEXT = 0x80;
const ASN_PRIVATE = 0xc0;
const ASN_PRIMITIVE = 0x0;
const ASN_CONSTRUCTOR = 0x20;
const SNMP_ACCESS_NONE = 0x0;
const SNMP_ACCESS_NOTIFY = 0x1;
const SNMP_ACCESS_READ_ONLY = 0x2;
const SNMP_ACCESS_READ_WRITE = 0x3;
const SNMP_ACCESS_READ_CREATE = 0x4;
const SNMPAPI_NOERROR = 0x1;
const SNMPAPI_ERROR = 0x0;
const SNMP_OUTPUT_TO_EVENTLOG = 0x4;
const DEFAULT_SNMP_PORT_UDP = 0xa1;
const DEFAULT_SNMP_PORT_IPX = 0x900f;
const DEFAULT_SNMPTRAP_PORT_UDP = 0xa2;
const DEFAULT_SNMPTRAP_PORT_IPX = 0x9010;
const SNMP_MAX_OID_LEN = 0x80;
const SNMP_MEM_ALLOC_ERROR = 0x1;
const SNMP_BERAPI_INVALID_LENGTH = 0xa;
const SNMP_BERAPI_INVALID_TAG = 0xb;
const SNMP_BERAPI_OVERFLOW = 0xc;
const SNMP_BERAPI_SHORT_BUFFER = 0xd;
const SNMP_BERAPI_INVALID_OBJELEM = 0xe;
const SNMP_PDUAPI_UNRECOGNIZED_PDU = 0x14;
const SNMP_PDUAPI_INVALID_ES = 0x15;
const SNMP_PDUAPI_INVALID_GT = 0x16;
const SNMP_AUTHAPI_INVALID_VERSION = 0x1e;
const SNMP_AUTHAPI_INVALID_MSG_TYPE = 0x1f;
const SNMP_AUTHAPI_TRIV_AUTH_FAILED = 0x20;
const ASN_CONTEXTSPECIFIC = 0x80;
const ASN_PRIMATIVE = 0x0;
const SNMP_MGMTAPI_TIMEOUT = 0x28;
const SNMP_MGMTAPI_SELECT_FDERRORS = 0x29;
const SNMP_MGMTAPI_TRAP_ERRORS = 0x2a;
const SNMP_MGMTAPI_TRAP_DUPINIT = 0x2b;
const SNMP_MGMTAPI_NOTRAPS = 0x2c;
const SNMP_MGMTAPI_AGAIN = 0x2d;
const SNMP_MGMTAPI_INVALID_CTL = 0x2e;
const SNMP_MGMTAPI_INVALID_SESSION = 0x2f;
const SNMP_MGMTAPI_INVALID_BUFFER = 0x30;
const MGMCTL_SETAGENTPORT = 0x1;
const MAXOBJIDSIZE = 0x80;
const MAXOBJIDSTRSIZE = 0x580;
const SNMPLISTEN_USEENTITY_ADDR = 0x0;
const SNMPLISTEN_ALL_ADDR = 0x1;
const SNMP_TRAP_COLDSTART = 0x0;
const SNMP_TRAP_WARMSTART = 0x1;
const SNMP_TRAP_LINKDOWN = 0x2;
const SNMP_TRAP_LINKUP = 0x3;
const SNMP_TRAP_AUTHFAIL = 0x4;
const SNMP_TRAP_EGPNEIGHBORLOSS = 0x5;
const SNMP_TRAP_ENTERPRISESPECIFIC = 0x6;
const SNMPAPI_NO_SUPPORT = 0x0;
const SNMPAPI_V1_SUPPORT = 0x1;
const SNMPAPI_V2_SUPPORT = 0x2;
const SNMPAPI_M2M_SUPPORT = 0x3;
const SNMPAPI_FAILURE = 0x0;
const SNMPAPI_SUCCESS = 0x1;
const SNMPAPI_ALLOC_ERROR = 0x2;
const SNMPAPI_CONTEXT_INVALID = 0x3;
const SNMPAPI_CONTEXT_UNKNOWN = 0x4;
const SNMPAPI_ENTITY_INVALID = 0x5;
const SNMPAPI_ENTITY_UNKNOWN = 0x6;
const SNMPAPI_INDEX_INVALID = 0x7;
const SNMPAPI_NOOP = 0x8;
const SNMPAPI_OID_INVALID = 0x9;
const SNMPAPI_OPERATION_INVALID = 0xa;
const SNMPAPI_OUTPUT_TRUNCATED = 0xb;
const SNMPAPI_PDU_INVALID = 0xc;
const SNMPAPI_SESSION_INVALID = 0xd;
const SNMPAPI_SYNTAX_INVALID = 0xe;
const SNMPAPI_VBL_INVALID = 0xf;
const SNMPAPI_MODE_INVALID = 0x10;
const SNMPAPI_SIZE_INVALID = 0x11;
const SNMPAPI_NOT_INITIALIZED = 0x12;
const SNMPAPI_MESSAGE_INVALID = 0x13;
const SNMPAPI_HWND_INVALID = 0x14;
const SNMPAPI_OTHER_ERROR = 0x63;
const SNMPAPI_TL_NOT_INITIALIZED = 0x64;
const SNMPAPI_TL_NOT_SUPPORTED = 0x65;
const SNMPAPI_TL_NOT_AVAILABLE = 0x66;
const SNMPAPI_TL_RESOURCE_ERROR = 0x67;
const SNMPAPI_TL_UNDELIVERABLE = 0x68;
const SNMPAPI_TL_SRC_INVALID = 0x69;
const SNMPAPI_TL_INVALID_PARAM = 0x6a;
const SNMPAPI_TL_IN_USE = 0x6b;
const SNMPAPI_TL_TIMEOUT = 0x6c;
const SNMPAPI_TL_PDU_TOO_BIG = 0x6d;
const SNMPAPI_TL_OTHER = 0xc7;
const MAXVENDORINFO = 0x20;
