// Copyright (c) 2020, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// Dart representations of common structs used in the Win32 API.

// THIS FILE IS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED DIRECTLY.

// ignore_for_file: camel_case_extensions, camel_case_types
// ignore_for_file: directives_ordering, unnecessary_getters_setters
// ignore_for_file: unused_field, unused_import

import 'dart:ffi';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

const FILE_DEVICE_SMARTCARD = 0x31;
const GUID_DEVINTERFACE_SMARTCARD_READER = 0x0;
const SCARD_ATR_LENGTH = 0x21;
const SCARD_PROTOCOL_UNDEFINED = 0x0;
const SCARD_PROTOCOL_T0 = 0x1;
const SCARD_PROTOCOL_T1 = 0x2;
const SCARD_PROTOCOL_RAW = 0x10000;
const SCARD_PROTOCOL_DEFAULT = 0x80000000;
const SCARD_PROTOCOL_OPTIMAL = 0x0;
const SCARD_POWER_DOWN = 0x0;
const SCARD_COLD_RESET = 0x1;
const SCARD_WARM_RESET = 0x2;
const MAXIMUM_ATTR_STRING_LENGTH = 0x20;
const MAXIMUM_SMARTCARD_READERS = 0xa;
const SCARD_CLASS_VENDOR_INFO = 0x1;
const SCARD_CLASS_COMMUNICATIONS = 0x2;
const SCARD_CLASS_PROTOCOL = 0x3;
const SCARD_CLASS_POWER_MGMT = 0x4;
const SCARD_CLASS_SECURITY = 0x5;
const SCARD_CLASS_MECHANICAL = 0x6;
const SCARD_CLASS_VENDOR_DEFINED = 0x7;
const SCARD_CLASS_IFD_PROTOCOL = 0x8;
const SCARD_CLASS_ICC_STATE = 0x9;
const SCARD_CLASS_PERF = 0x7ffe;
const SCARD_CLASS_SYSTEM = 0x7fff;
const SCARD_T0_HEADER_LENGTH = 0x7;
const SCARD_T0_CMD_LENGTH = 0x5;
const SCARD_T1_PROLOGUE_LENGTH = 0x3;
const SCARD_T1_EPILOGUE_LENGTH = 0x2;
const SCARD_T1_EPILOGUE_LENGTH_LRC = 0x1;
const SCARD_T1_MAX_IFS = 0xfe;
const SCARD_UNKNOWN = 0x0;
const SCARD_ABSENT = 0x1;
const SCARD_PRESENT = 0x2;
const SCARD_SWALLOWED = 0x3;
const SCARD_POWERED = 0x4;
const SCARD_NEGOTIABLE = 0x5;
const SCARD_SPECIFIC = 0x6;
const SCARD_READER_SWALLOWS = 0x1;
const SCARD_READER_EJECTS = 0x2;
const SCARD_READER_CONFISCATES = 0x4;
const SCARD_READER_CONTACTLESS = 0x8;
const SCARD_READER_TYPE_SERIAL = 0x1;
const SCARD_READER_TYPE_PARALELL = 0x2;
const SCARD_READER_TYPE_KEYBOARD = 0x4;
const SCARD_READER_TYPE_SCSI = 0x8;
const SCARD_READER_TYPE_IDE = 0x10;
const SCARD_READER_TYPE_USB = 0x20;
const SCARD_READER_TYPE_PCMCIA = 0x40;
const SCARD_READER_TYPE_TPM = 0x80;
const SCARD_READER_TYPE_NFC = 0x100;
const SCARD_READER_TYPE_UICC = 0x200;
const SCARD_READER_TYPE_NGC = 0x400;
const SCARD_READER_TYPE_EMBEDDEDSE = 0x800;
const SCARD_READER_TYPE_VENDOR = 0xf0;
const STATUS_LOGON_FAILURE = 0xc000006d;
const STATUS_WRONG_PASSWORD = 0xc000006a;
const STATUS_PASSWORD_EXPIRED = 0xc0000071;
const STATUS_PASSWORD_MUST_CHANGE = 0xc0000224;
const STATUS_ACCESS_DENIED = 0xc0000022;
const STATUS_DOWNGRADE_DETECTED = 0xc0000388;
const STATUS_AUTHENTICATION_FIREWALL_FAILED = 0xc0000413;
const STATUS_ACCOUNT_DISABLED = 0xc0000072;
const STATUS_ACCOUNT_RESTRICTION = 0xc000006e;
const STATUS_ACCOUNT_LOCKED_OUT = 0xc0000234;
const STATUS_ACCOUNT_EXPIRED = 0xc0000193;
const STATUS_LOGON_TYPE_NOT_GRANTED = 0xc000015b;
const STATUS_NO_SUCH_LOGON_SESSION = 0xc000005f;
const STATUS_NO_SUCH_USER = 0xc0000064;
const CRED_MAX_STRING_LENGTH = 0x100;
const CRED_MAX_GENERIC_TARGET_NAME_LENGTH = 0x7fff;
const CRED_MAX_TARGETNAME_NAMESPACE_LENGTH = 0x100;
const CRED_MAX_TARGETNAME_ATTRIBUTE_LENGTH = 0x100;
const CRED_MAX_VALUE_SIZE = 0x100;
const CRED_MAX_ATTRIBUTES = 0x40;
const CRED_LOGON_TYPES_MASK = 0xf000;
const CRED_TI_SERVER_FORMAT_UNKNOWN = 0x1;
const CRED_TI_DOMAIN_FORMAT_UNKNOWN = 0x2;
const CRED_TI_ONLY_PASSWORD_REQUIRED = 0x4;
const CRED_TI_USERNAME_TARGET = 0x8;
const CRED_TI_CREATE_EXPLICIT_CRED = 0x10;
const CRED_TI_WORKGROUP_MEMBER = 0x20;
const CRED_TI_DNSTREE_IS_DFS_SERVER = 0x40;
const CRED_TI_VALID_FLAGS = 0xf07f;
const CERT_HASH_LENGTH = 0x14;
const CREDUI_MAX_MESSAGE_LENGTH = 0x400;
const CREDUI_MAX_CAPTION_LENGTH = 0x80;
const CREDUI_MAX_GENERIC_TARGET_LENGTH = 0x7fff;
const CREDUIWIN_IGNORE_CLOUDAUTHORITY_NAME = 0x40000;
const CREDUIWIN_DOWNLEVEL_HELLO_AS_SMART_CARD = 0x80000000;
const CRED_PRESERVE_CREDENTIAL_BLOB = 0x1;
const CRED_CACHE_TARGET_INFORMATION = 0x1;
const CRED_ALLOW_NAME_RESOLUTION = 0x1;
const CRED_PROTECT_AS_SELF = 0x1;
const CRED_PROTECT_TO_SYSTEM = 0x2;
const CRED_UNPROTECT_AS_SELF = 0x1;
const CRED_UNPROTECT_ALLOW_TO_SYSTEM = 0x2;
const SCARD_SCOPE_TERMINAL = 0x1;
const SCARD_PROVIDER_PRIMARY = 0x1;
const SCARD_PROVIDER_CSP = 0x2;
const SCARD_PROVIDER_KSP = 0x3;
const SCARD_STATE_UNPOWERED = 0x400;
const SCARD_SHARE_EXCLUSIVE = 0x1;
const SCARD_SHARE_SHARED = 0x2;
const SCARD_SHARE_DIRECT = 0x3;
const SCARD_LEAVE_CARD = 0x0;
const SCARD_RESET_CARD = 0x1;
const SCARD_UNPOWER_CARD = 0x2;
const SCARD_EJECT_CARD = 0x3;
const SC_DLG_MINIMAL_UI = 0x1;
const SC_DLG_NO_UI = 0x2;
const SC_DLG_FORCE_UI = 0x4;
const SCERR_NOCARDNAME = 0x4000;
const SCERR_NOGUIDS = 0x8000;
const SCARD_AUDIT_CHV_FAILURE = 0x0;
const SCARD_AUDIT_CHV_SUCCESS = 0x1;
const CREDSSP_SERVER_AUTH_NEGOTIATE = 0x1;
const CREDSSP_SERVER_AUTH_CERTIFICATE = 0x2;
const CREDSSP_SERVER_AUTH_LOOPBACK = 0x4;
const SECPKG_ALT_ATTR = 0x80000000;
const SECPKG_ATTR_C_FULL_IDENT_TOKEN = 0x80000085;
const CREDSSP_CRED_EX_VERSION = 0x0;
const CREDSSP_FLAG_REDIRECT = 0x1;
