// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//
// dart run tool/generate_asset_hashes.dart
//

/// A map from asset file names to their MD5 hashes.
///
/// Used to verify the integrity of downloaded assets.
const assetHashes = <String, String>{
  'win32_windows_arm64.dll': '93d3bc4a11b9ae4984861aa8f8b5cdd7',
  'win32_windows_x64.dll': 'f4c83eda1fd91b4214bf5af524f9d35c',
};
