// THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY.
//
// TO UPDATE, RUN:
//
// dart run tool/generate_asset_hashes.dart
//

/// A map from asset file names to their MD5 hashes.
///
/// Used to verify the integrity of downloaded assets.
const assetHashes = <String, String>{
  'win32_windows_arm64.dll': 'a5a2b0f50bb3fbb7399640da837d03a7',
  'win32_windows_x64.dll': '6bb3eabcb9cd62eb9d74b71c224bdb0b',
};
