name: Check Code Generation

on:
  pull_request:
    paths:
      - .github/workflows/code_generation.yml
      - pubspec.yaml
      - packages/generator/bin/**
      - packages/generator/lib/**
      - packages/generator/pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/code_generation.yml
      - pubspec.yaml
      - packages/generator/bin/**
      - packages/generator/lib/**
      - packages/generator/pubspec.yaml

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Activate Melos
        uses: bluefireteam/melos-action@2982f8e4fc92440a219490009d6d05195cb1a6a5

      - name: 📦 Install Workspace Dependencies
        run: dart pub get

      - name: 🚀 Run Code Generation
        run: melos run generate

      - name: 🔍 Verify Code Generation
        run: git diff --exit-code
