name: Check Code Generation

on:
  pull_request:
    paths:
      - .github/workflows/code_generation.yml
      - pubspec.yaml
      - packages/generator/bin/**
      - packages/generator/lib/**
      - packages/generator/pubspec.yaml
  push:
    branches: [main]
    paths:
      - .github/workflows/code_generation.yml
      - pubspec.yaml
      - packages/generator/bin/**
      - packages/generator/lib/**
      - packages/generator/pubspec.yaml

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Activate Melos
        uses: bluefireteam/melos-action@v3

      - name: 📦 Install Workspace Dependencies
        run: dart pub get

      - name: 🚀 Run Code Generation
        run: melos run generate

      - name: 🔍 Verify Code Generation
        run: git diff --exit-code
