name: Sync Labels

on:
  push:
    branches: [main]
    paths:
      - .github/labels.yml
  workflow_dispatch:

permissions:
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: 🚀 Run Label Sync
        uses: srealmoreno/label-sync-action@850ba5cef2b25e56c6c420c4feed0319294682fd
        with:
          clean-labels: true
          config-file: |
            .github/labels.yml
            https://raw.githubusercontent.com/halildurmus/workflows/main/.github/labels.yml
